# Deteccion de texto innecesario

Este archivo busca ir mostrando noticias con ciertas palabras. frases o caracteres no deseados. y la logica implementada para su eliminacion


## elpais20140911184708Noticias.txt

In [1]:
# Estos archivos estan en la raiz del repositorio, NO ESTAN SUBIDOS.
# Son el resultado de una primera extraccion de los textos y alguna correccion.
archivo_el_pais_1 = '../elpais20140911184708Noticias-ORIGINAL.txt'

In [2]:
! pip install Unidecode

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import re
from unidecode import unidecode

In [4]:
def sanitice_text(txt):

  # estoy interesado en obtener todos los caracteres que no sean:

  # 1. ASCII
  whiteList = '\x00-\x7F'

  # 2. ¿ ¡ tildes y enies
  whiteList += '¿¡À-ÿñÑ'

  regex = r'[^{}]'.format(whiteList)
  patt = re.compile(regex)

  sanitice_char = lambda c: unidecode(c) if patt.match(c) else c
  
  return "".join([sanitice_char(c) for c in txt])

Ejemplo de sanitizacion


In [5]:
txt = """Hola, este es un texto multilinea.

“¡¿había ‘existido’ `<dudas>`?!” François 85° ✔️-❤️-💲-😎-€-$-¥

Saludos,
  JP.
"""

print(sanitice_text(txt))

Hola, este es un texto multilinea.

"¡¿había 'existido' `<dudas>`?!" François 85deg ----EUR-$-Y=

Saludos,
  JP.



In [6]:
reader = open(archivo_el_pais_1, "r+")
lines = reader.readlines()
print(len(lines))

120692


In [7]:
lines[0][:500]

'- Nacional La formación de docentes en la región es "deficiente" Un estudio internacional que incluye a Uruguay, asegura que son escasos los maestros que demuestran talento Personas poco talentosas, con falta de preparación y pertenecientes a sectores carenciados. Esas características se atribuyen a los docentes latinoamericanos en un estudio internacional, en el que se establece que la enseñanza que imparten "ha empeorado" y que además perjudica especialmente a los sectores de menores rec'

### Chequeo caracteres con codificacion incorrecta: eñes y tildes

In [8]:
print('además' == 'además')
print('á' == 'á')

False
False


In [9]:
print('Varieté' == 'Varieté')
print('é' == 'é')

False
False


In [10]:
print('características' == 'características')
print('í' == 'í')

False
False


In [11]:
print('formación' == 'formación')
print('ó' == 'ó')

False
False


In [12]:
print('según' == 'según')
print('ú' == 'ú')

False
False


In [13]:
print('enseñanza' == 'enseñanza')
print('ñ' == 'ñ')

False
False


In [14]:
'ñ'.upper() == 'Ñ'

False

#### Aplico correcciones

In [15]:
replace_dict = {
        'á': 'á',
        'é': 'é',
        'í': 'í',
        'ó': 'ó',
        'ú': 'ú',
        'ñ': 'ñ',
        'Á': 'Á',
        'É': 'É',
        'Í': 'Í',
        'Ó': 'Ó',
        'Ú': 'Ú',
        'Ñ': 'Ñ'
        }
replace_dict

{'á': 'á',
 'é': 'é',
 'í': 'í',
 'ó': 'ó',
 'ú': 'ú',
 'ñ': 'ñ',
 'Á': 'Á',
 'É': 'É',
 'Í': 'Í',
 'Ó': 'Ó',
 'Ú': 'Ú',
 'Ñ': 'Ñ'}

In [16]:
str_example = lines[0][:500]
for original, replacement in replace_dict.items():
  str_example = str_example.replace(original, replacement)
str_example

'- Nacional La formación de docentes en la región es "deficiente" Un estudio internacional que incluye a Uruguay, asegura que son escasos los maestros que demuestran talento Personas poco talentosas, con falta de preparación y pertenecientes a sectores carenciados. Esas características se atribuyen a los docentes latinoamericanos en un estudio internacional, en el que se establece que la enseñanza que imparten "ha empeorado" y que además perjudica especialmente a los sectores de menores rec'

In [17]:
# chequeo
str_example[:23] == '- Nacional La formación'

True

In [18]:
auxiliar_full_lines = ''.join(lines)
# reemplazo tildes

replace_dict = {
        'á': 'á',
        'é': 'é',
        'í': 'í',
        'ó': 'ó',
        'ú': 'ú',
        'ñ': 'ñ',
        'Á': 'Á',
        'É': 'É',
        'Í': 'Í',
        'Ó': 'Ó',
        'Ú': 'Ú',
        'Ñ': 'Ñ'
        }

for original, replacement in replace_dict.items():
  print(replacement)
  auxiliar_full_lines = auxiliar_full_lines.replace(original, replacement)

#sanitizo
print('saniticing')
auxiliar_full_lines = sanitice_text(auxiliar_full_lines)

á
é
í
ó
ú
ñ
Á
É
Í
Ó
Ú
Ñ
saniticing


In [21]:
auxiliar_full_lines[:999]

'- Nacional La formación de docentes en la región es "deficiente" Un estudio internacional que incluye a Uruguay, asegura que son escasos los maestros que demuestran talento Personas poco talentosas, con falta de preparación y pertenecientes a sectores carenciados. Esas características se atribuyen a los docentes latinoamericanos en un estudio internacional, en el que se establece que la enseñanza que imparten "ha empeorado" y que además perjudica especialmente a los sectores de menores recursos. El diagnóstico, que abarca a países de América Latina -entre ellos a Uruguay- coincide con la apreciación que el año pasado realizó el vicepresidente del Consejo Directivo Central (Codicen), José Pedro Barrán, sobre la realidad de los docentes del país. El 29 de setiembre del año pasado en el Parlamento, Barrán aseguró que en Uruguay es "muy difícil conseguir un docente de calidad" porque "los candidatos que se presentan son los menos calificados académicamente". Además, indicó que "como los s

### Texto "Utilidades" al final

In [22]:
print(lines[91063])

Encuesta de popularidad de equipos NANDO PARRADO Como se preveía, en la encuesta realizada por la FIA, sobre la popularidad de los equipos de F1, Ferrari está indiscutiblemente al tope. En segundo lugar y no demasiado lejos, está McLaren, en tercer lugar está Renault, cuarto está Williams y en quinto lugar está Honda. Lo que más me ha llamado la atención, es la baja popularidad de equipos como el Red Bull y Toyota, que con sus inversiones multimillonarias, apenas logran un 1% y 2% de los votos respectivamente. No sé si estas inversiones realmente se justifican, si frente a la recordación de los aficionados, solamente logran ese pequeño porcentaje. No debemos olvidar que la fascinación de las grandes marcas en F1, se ha contraído a lo largo de varias décadas, con grandes carreras, estupendos triunfos y la colaboración de inolvidables pilotos en cada una de ellas. Grandes constructores, siempre han tenido grandes motores y grandes pilotos, para lograr ese aura de leyendas.

Encuesta de popularidad de equipos NANDO PARRADO Como se preveía, en la encuesta realizada por la FIA, sobre la popularidad de los equipos de F1, Ferrari está indiscutiblemente al tope. En segundo lugar y no demasiado lejos, está McLaren, en tercer lugar está Renault, cuarto está Williams y en quinto lugar está Honda. Lo que más me ha llamado la atención, es la baja popularidad de equipos como el Red Bull y Toyota, que con sus inversiones multimillonarias, apenas logran un 1% y 2% de los votos respectivamente. No sé si estas inversiones realmente se justifican, si frente a la recordación de los aficionados, solamente logran ese pequeño porcentaje. No debemos olvidar que la fascinación de las grandes marcas en F1, se ha contraído a lo largo de varias décadas, con grandes carreras, estupendos triunfos y la colaboración de inolvidables pilotos en cada una de ellas. Grandes constructores, siempre han tenido grandes motores y grandes pilotos, para lograr ese aura de leyendas. Tal vez dentro de unos cuantos años, Red Bull de F1, pueda erizar los pelos de un aficionado, si ha logrado varios campeonatos del mundo y haya tenido asociaciones como Fangio-Ferrari, Senna-McLaren, Lauda-Ferrari, Stewart-Tyrrel, Prost-McLaren, Clark-Lotus... No le suenan mejor que Liuzzi-Red Bull?  **Utilidades**


#### Solucion

In [23]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto Utilidades
pattern = r"Utilidades"
results = re.findall(pattern, str_text)
print(len(results))

# cantidad de ocurrencias con texto Utilidades y salto de linea
pattern_1 = r"Utilidades\n"
results_1 = re.findall(pattern_1, str_text)
print(len(results_1))

# Analizo la diferencia y si tendria que tenerlo en cuenta
pattern_difference = r"Utilidades........."
results_d = re.findall(pattern_difference, str_text)
print(len(results_d))
print(results_d)

21611
21607
4
['Utilidades del estu', 'Utilidades garantiz', 'Utilidades de El Pa', 'Utilidades, Arudur,']


In [24]:
replace_pattern = r"Utilidades\n"
result = re.sub(replace_pattern, '', lines[91063])  
print(result)

Encuesta de popularidad de equipos NANDO PARRADO Como se preveía, en la encuesta realizada por la FIA, sobre la popularidad de los equipos de F1, Ferrari está indiscutiblemente al tope. En segundo lugar y no demasiado lejos, está McLaren, en tercer lugar está Renault, cuarto está Williams y en quinto lugar está Honda. Lo que más me ha llamado la atención, es la baja popularidad de equipos como el Red Bull y Toyota, que con sus inversiones multimillonarias, apenas logran un 1% y 2% de los votos respectivamente. No sé si estas inversiones realmente se justifican, si frente a la recordación de los aficionados, solamente logran ese pequeño porcentaje. No debemos olvidar que la fascinación de las grandes marcas en F1, se ha contraído a lo largo de varias décadas, con grandes carreras, estupendos triunfos y la colaboración de inolvidables pilotos en cada una de ellas. Grandes constructores, siempre han tenido grandes motores y grandes pilotos, para lograr ese aura de leyendas.

In [25]:
# analisis de recorrer todo el texto
replace_pattern = r"Utilidades\n"
total_result = re.sub(replace_pattern, '', str_text)  

# cantidad de ocurrencias con texto Utilidades
pattern = r"Utilidades"
results = re.findall(pattern, total_result)
print(len(results))

# cantidad de ocurrencias con texto Utilidades y salto de linea
pattern_1 = r"Utilidades\n"
results_1 = re.findall(pattern_1, total_result)
print(len(results_1))


4
0


### Caracteres extranios

Los casos con el texto extranio se van a eliminar

In [26]:
print(lines[35479])

delincuencia | En Col�n cacerolearon vecinos y comerciantes | Medidas de seguridad en Casab� donde fue asesinado un chofer de �mnibus | Reclamos desde Salto y Artigas Inseguridad genera m�ltiples reclamos GUSTAVO TRINIDAD El Ministerio del Interior enfrenta varios reclamos de seguridad por parte de vecinos de distintas zonas de Montevideo �como el Cerro, Col�n, Casab� y Sayago�, as� como del interior del pa�s, donde se realizaron movilizaciones en Artigas, Salto y Rocha. La situaci�n en algunos barrios es insostenible y en varias zonas de Montevideo los vecinos se est�n organizando para protegerse de los delincuentes. Ayer los vecinos y comerciantes de Col�n y otros barrios cercanos hicieron una protesta en la avenida Garz�n. "No m�s impunidad en la delincuencia juvenil", exig�an en sus pancartas y ped�an que se revise el C�digo de la Ni�ez y la Adolescencia que, seg�n dicen, "protege a los delincuentes juveniles". Jorge Ruglio, integrante de la Asociaci�n de Comerciantes de Col�n, dij

### Texto "Vota por esta noticia:" al final

In [27]:
print(lines[43765])

MATÍAS CASTRO Aunque las salas de cine anticipan más y más secuelas de sagas multimillonarias, este año irrumpirán algunas producciones que apuntan al entretenimiento masivo y que arrancan de cero. Pero no se trata de apuestas originales. Iron Man 3 ha recaudado 102 millones de dólares en funciones en Latinoamérica. Si a esto se le suma la taquilla del resto del planeta, se verá que en este período el film suma 678 millones de dólares. Y todavía tiene varias semanas más de exhibición. Esta es la prueba más reciente y caliente de que las sagas cinematográficas con grandes efectos especiales son el gran fenómeno de inicios del siglo XXI para el cine. Pero no todo son continuaciones, afortunadamente. Porque también hay películas que presentan personajes nuevos e historias diferentes y que... parecen apuntar a generar nuevas sagas. Durante la última década Hollywood ha buscado apoyarse en franquicias reconocidas, para generar secuelas y negocios crecientes. Progresivame

MATÍAS CASTRO Aunque las salas de cine anticipan más y más secuelas de sagas multimillonarias, este año irrumpirán algunas producciones que apuntan al entretenimiento masivo y que arrancan de cero. Pero no se trata de apuestas originales. Iron Man 3 ha recaudado 102 millones de dólares en funciones en Latinoamérica. Si a esto se le suma la taquilla del resto del planeta, se verá que en este período el film suma 678 millones de dólares. Y todavía tiene varias semanas más de exhibición. Esta es la prueba más reciente y caliente de que las sagas cinematográficas con grandes efectos especiales son el gran fenómeno de inicios del siglo XXI para el cine. Pero no todo son continuaciones, afortunadamente. Porque también hay películas que presentan personajes nuevos e historias diferentes y que... parecen apuntar a generar nuevas sagas. Durante la última década Hollywood ha buscado apoyarse en franquicias reconocidas, para generar secuelas y negocios crecientes. Progresivamente, las películas de Piratas del Caribe, Transformers o Harry Potter fueron recaudando cada vez más dinero. La consecuencia de esto es que año a año los espectadores ven en el verano del norte, otoño e invierno del Río de la Plata, una andanada de costosas películas de entretenimientos que son continuaciones. Este año aparecen tres grandes excepciones a la regla que, aunque parezca paradójico, cumplen con varios preceptos de la industria. Por un lado está Titanes del Pacífico, de Guillermo del Toro. Luego está El Llanero Solitario, del equipo de Piratas del Caribe. Y por el otro la costosa y problemática Guerra Mundial Z, protagonizada por Brad Pitt. El quiebre de la regla que plantean es que no se apoyan en personajes conocidos y son historias nuevas para el cine. El punto común que mantienen es que se trata de producciones de despliegue que apuntan al entretenimiento masivo, la acción y a los efectos especiales. De las tres la única que tiene una idea más o menos original y poco (o nada) explorada por el cine estadounidense, es Titanes del Pacífico. Dirigida por Guillermo del Toro, se ambienta en un futuro cercano y cuenta el enfrentamiento entre una raza de monstruos gigantes que surgen del Océano Pacífico y los seres humanos, que utilizan enormes robots tripulados. La propuesta, hasta ahora, parecía más apta para una película japonesa que para una producción de Hollywood, pero tras el éxito de Transformers los productores apuntan a un público ya familiarizado con esta clase de fantasías. Por otra parte, el hecho de que dirija el mexicano Guillermo del Toro (El laberinto del Fauno, Hellboy 1 y 2), le asegura un ritmo y una estética casi de autor. Trailer: Pacific Rim En el contexto actual, apuestas como esa son consideradas un riesgo, al menos para los productores y los estudios. El año pasado John Carter, que se basaba en una serie de novelas pero que para el público en general era nuevo, fue un total fracaso. La consecuencia fue que el siguiente paso del director Andrew Stanton fue meterse de lleno a preparar la secuela de su exitosísima Buscando a Nemo. Hollywood puede dar grandes oportunidades pero también es el centro de una industria que vive del éxito. Si no hay éxito, hay problemas. La que se apoya en un éxito probado es Guerra Mundial Z, con Brad Pitt. Cuenta la historia de un agente de las Naciones Unidas que recorre el mundo en medio de una epidemia de zombis, intentando buscar una cura. Se basa en una novela de Max Brooks, el hijo de Mel Brooks, quien logró un enorme éxito editorial en Estados Unidos. La novela es un tanto distinta ya que trata de un agente de las Naciones Unidas que recorre el mundo entrevistando protagonistas clave durante el estallido, clímax y conclusión de la epidemia zombi. De esa forma cada capítulo es una entrevista o un testimonio literal independiente y la narración central trata, en realidad, sobre cómo el planeta enfrentó el asunto. Trailer: Guerra Mundial Z La película costó, según algunos reportes, unos 400 millones de dólares, lo que la convertiría en la producción más cara estrenada después de Avatar. Hay muchas versiones encontradas en torno a esta película. Brad Pitt compró los derechos de la novela hace cinco años. El guión fue escrito y reescrito numerosas veces, cosa relativamente normal en Hollywood. En este caso, además, hubo cambios de último momento, decisiones drásticas sobre la historia y reelaboraciones sobre el tramo final del film, impulsados supuestamente porque no había acuerdo ni satisfacción con lo que se había hecho. Además, iba a ser estrenada en diciembre pero Paramount resolvió posponerla y concentrarse en el lanzamiento de Jack Reacher, con Tom Cruise. Y, además, de esa forma, al estrenarla a mediados de año la colocan en medio de la mayor zafra de las boleterías. El Llanero Solitario, por su lado, retoma al viejo y querido personaje, dirigido por Gore Verbinsky, el de Piratas del Caribe. El giro, esta vez, es evidente ya que a pesar del título, el peso está en manos de Toro, el indio que encarna Johnny Depp. No hay dudas de que si funciona (y es probable que lo haga), habrá más Llanero y Toro para las futuras vacaciones de invierno. Trailer: El Llanero Solitario Se vienen más secuelas de viejos éxitos A lo largo de los próximos meses, comenzando desde las próximas semanas, los cines volverán a albergar una andanada de producciones estadounidenses caras que continúan aventuras previas y que recaudaron muchísimo dinero en todo el mundo. La que llega el último viernes de este mes es ¿Qué pasó ayer? 3 anunciado final de las aventuras del grupo de amigos que en cada despedida de solteros terminan en las situaciones más disparatadas imaginables. En este caso los avances insinúan que la historia conectará con personajes y situaciones de las dos primeras películas, pero a una escala mucho mayor. En agosto llegará a Uruguay Star Trek hacia la oscuridad, dirigida por J. J. Abrams, continuando la historia de la película anterior y enlazando con la saga de Viaje a las estrellas. Habrá más superhéroes en el camino, ya que se verá en la segunda mitad del año Thor, un mundo oscuro, que sigue las aventuras del personaje de Marvel Comics. Y en pocas semanas llegará Rápido y furioso 6, continuación que, a diferencia de otras sextas partes, fue hecha con más dinero y despliegue aún. No todo será cosa de adultos y explosiones, sino que habrá secuelas para niños. Llegarán Monsters University, secuela de Monsters Inc. y Mi villano favorito 2. Dos viejos personajes que se recrean desde este año El Llanero Solitario apareció por primera vez en un programa radial de 1933, creado por el libretista Fran Striker. Ha conocido las más variadas versiones, desde los seriales de cine hasta los dibujos animados, las historietas y las series de televisión. Su regreso al cine supone un rescate interesante de un clásico querido por generaciones más veteranas pero no exactamente una apuesta a la originalidad. Lo mismo sucede con El hombre de acero, la nueva película de Superman que se estrenará en junio. Esta vez el británico Christopher Nolan y el director estadounidense Zack Snyder apuntan a relanzar al superhéroe más famoso de todos, con una aproximación que promete ser más realista y épica al mismo tiempo. Son dos franquicias viejas que se relanzan a lo grande dentro de los próximos meses. `Vota por esta noticia:`


#### Solucion

In [28]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto Vota por esta noticia
pattern = r"Vota por esta noticia:"
results = re.findall(pattern, str_text)
print(len(results))

# cantidad de ocurrencias con texto -Vota por esta noticia- y salto de linea
pattern_1 = r"Vota por esta noticia:\n"
results_1 = re.findall(pattern_1, str_text)
print(len(results_1))

# # Analizo la diferencia y si tendria que tenerlo en cuenta
pattern_difference = r"..............Vota por esta noticia:........."
results_d = re.findall(pattern_difference, str_text)
print(len(results_d))
for example in results_d[:20]:
  print(example)

## CONCLUSION - tengo que eliminar todos, aunque no esten al final

41814
40527
1287
del sábado 9. Vota por esta noticia: vea el v
ercado local. Vota por esta noticia: CASO SUÁ
e nuevo otra. Vota por esta noticia: vea el v
mo Municipal. Vota por esta noticia: BARCELON
n maduración. Vota por esta noticia: BARCELON
 la tonelada. Vota por esta noticia: CASO SUÁ
ra los toros. Vota por esta noticia: vea el v
ráfico: BE .  Vota por esta noticia: CASO SUÁ
8,7 millones. Vota por esta noticia: COPA Lib
ercado local. Vota por esta noticia: COPA Lib
la epilepsia. Vota por esta noticia: COPA Lib
do de muerte. Vota por esta noticia: BARCELON
500 dólares". Vota por esta noticia: BARCELON
do trimestre. Vota por esta noticia: vea el v
ga click aquí Vota por esta noticia: COPA Lib
solucionarlo. Vota por esta noticia: BARCELON
ricas Km. 18. Vota por esta noticia: vea el v
inistrativa.  Vota por esta noticia: A - NOTI
as ediciones. Vota por esta noticia: COPA Lib
l suministro. Vota por esta noticia: BARCELON


In [29]:
replace_pattern = r"Vota por esta noticia:"
result = re.sub(replace_pattern, '', lines[43765])  
print(result)

MATÍAS CASTRO Aunque las salas de cine anticipan más y más secuelas de sagas multimillonarias, este año irrumpirán algunas producciones que apuntan al entretenimiento masivo y que arrancan de cero. Pero no se trata de apuestas originales. Iron Man 3 ha recaudado 102 millones de dólares en funciones en Latinoamérica. Si a esto se le suma la taquilla del resto del planeta, se verá que en este período el film suma 678 millones de dólares. Y todavía tiene varias semanas más de exhibición. Esta es la prueba más reciente y caliente de que las sagas cinematográficas con grandes efectos especiales son el gran fenómeno de inicios del siglo XXI para el cine. Pero no todo son continuaciones, afortunadamente. Porque también hay películas que presentan personajes nuevos e historias diferentes y que... parecen apuntar a generar nuevas sagas. Durante la última década Hollywood ha buscado apoyarse en franquicias reconocidas, para generar secuelas y negocios crecientes. Progresivame

### Texto "Escribe tu comentario" al final
### Texto con formato :: texto ::

In [30]:
print(lines[104738])

Los albivioletas volvieron a robarle puntos al aurinegro, aunque esta vez no los tres. Fue empate a 1 el día del retorno de Antonio Pacheco. :: Último Momento :: Aseguran que sería "inadecuado" e "ineficaz" porque el Estado no puede controlar y ser parte a la vez. :: Nacional :: El MPP impulsará un juicio político contra la SCJ por la declaración de inconstitucional de una ley de octubre de 2011 que dejó sin efecto la ley la Caducidad. :: Último Momento :: Los habitantes de las humildes viviendas de chapa y madera intentaron apagar el fuego junto a sus vecinos pero no pudieron evitar las pérdidas totales. :: Último Momento :: El sábado 2 de marzo será el turno de La 33 y el sábado 9 se podrá disfrutar de Olodum por la pantalla de dicho canal. :: Último Momento :: El vicepresidente Nicolás Maduro realizó una conferencia de prensa despúes de visitarlo en el Hospital Militar. :: Último Momento :: El movimiento "antisistema" del cómico Beppe Grillo puso a temblar a la c

Los albivioletas volvieron a robarle puntos al aurinegro, aunque esta vez no los tres. Fue empate a 1 el día del retorno de Antonio Pacheco. :: Último Momento :: Aseguran que sería "inadecuado" e "ineficaz" porque el Estado no puede controlar y ser parte a la vez. `:: Nacional ::` El MPP impulsará un juicio político contra la SCJ por la declaración de inconstitucional de una ley de octubre de 2011 que dejó sin efecto la ley la Caducidad. `:: Último Momento ::` Los habitantes de las humildes viviendas de chapa y madera intentaron apagar el fuego junto a sus vecinos pero no pudieron evitar las pérdidas totales. :: Último Momento :: El sábado 2 de marzo será el turno de La 33 y el sábado 9 se podrá disfrutar de Olodum por la pantalla de dicho canal. :: Último Momento :: El vicepresidente Nicolás Maduro realizó una conferencia de prensa despúes de visitarlo en el Hospital Militar. :: Último Momento :: El movimiento "antisistema" del cómico Beppe Grillo puso a temblar a la clase política italiana después del cierre apoteósico el viernes de su campaña para las .. :: Espectáculos :: La gran cantidad de directores de cine "serio" que se sumó a la nueva serie "House of cards" no es más que la punta del iceberg: cada vez más pesos pesados de la gran .. :: Fútbol Nacional :: Maximiliano Rodríguez, dos veces de penal, le dio la victoria por 2-1 a al bohemio. :: Último Momento :: Miles de personas se manifiestan en más de 80 ciudades contra "un golpe de Estado financiero". `Escribe tu comentario`


#### Solucion

#### Parseo de "Escribe tu comentario"



In [31]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto Utilidades
pattern = r"Escribe tu comentario"
results = re.findall(pattern, str_text)
print(len(results))

# cantidad de ocurrencias con texto Utilidades y salto de linea
pattern_1 = r"Escribe tu comentario\n"
results_1 = re.findall(pattern_1, str_text)
print(len(results_1))

# estan al final siempre


171
171


In [32]:
replace_pattern = r"Escribe tu comentario\n"
result = re.sub(replace_pattern, '', lines[104738])  
print(result)

Los albivioletas volvieron a robarle puntos al aurinegro, aunque esta vez no los tres. Fue empate a 1 el día del retorno de Antonio Pacheco. :: Último Momento :: Aseguran que sería "inadecuado" e "ineficaz" porque el Estado no puede controlar y ser parte a la vez. :: Nacional :: El MPP impulsará un juicio político contra la SCJ por la declaración de inconstitucional de una ley de octubre de 2011 que dejó sin efecto la ley la Caducidad. :: Último Momento :: Los habitantes de las humildes viviendas de chapa y madera intentaron apagar el fuego junto a sus vecinos pero no pudieron evitar las pérdidas totales. :: Último Momento :: El sábado 2 de marzo será el turno de La 33 y el sábado 9 se podrá disfrutar de Olodum por la pantalla de dicho canal. :: Último Momento :: El vicepresidente Nicolás Maduro realizó una conferencia de prensa despúes de visitarlo en el Hospital Militar. :: Último Momento :: El movimiento "antisistema" del cómico Beppe Grillo puso a temblar a la c

#### Solucion


#### Parseo de texto formato :: AA ::



In [33]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto Utilidades
pattern = r":: .*? ::"
results = re.findall(pattern, str_text)
print(len(results))

18460


In [34]:
replace_pattern = r":: .*? ::"
result = re.sub(replace_pattern, '', lines[104738])  
print(result)

Los albivioletas volvieron a robarle puntos al aurinegro, aunque esta vez no los tres. Fue empate a 1 el día del retorno de Antonio Pacheco.  Aseguran que sería "inadecuado" e "ineficaz" porque el Estado no puede controlar y ser parte a la vez.  El MPP impulsará un juicio político contra la SCJ por la declaración de inconstitucional de una ley de octubre de 2011 que dejó sin efecto la ley la Caducidad.  Los habitantes de las humildes viviendas de chapa y madera intentaron apagar el fuego junto a sus vecinos pero no pudieron evitar las pérdidas totales.  El sábado 2 de marzo será el turno de La 33 y el sábado 9 se podrá disfrutar de Olodum por la pantalla de dicho canal.  El vicepresidente Nicolás Maduro realizó una conferencia de prensa despúes de visitarlo en el Hospital Militar.  El movimiento "antisistema" del cómico Beppe Grillo puso a temblar a la clase política italiana después del cierre apoteósico el viernes de su campaña para las ..  La gran cantidad de dire

### Texto "No salgas a la calle sin" al final

In [35]:
print(lines[14903])

x Alianzas de narcos llegan a Uruguay Drogas. Tras la caída de grupo mexicano amenazaron a jerarcas Extensión de cultivos de cocaína en Bolivia preocupa a autoridades En 9 meses incautaron más de 700 kilos plantados allí | Según un informe internacional sobre tácticas de países ¿Narcotraficantes mexicanos rescatados del Penal de Libertad en helicópteros? ¿Amenazas de muerte contra toda la cúpula del Ministerio del Interior? Una sombra que se alarga por todo el continente y finalmente llega a Uruguay. El fenómeno se llama "hiperproducción de drogas". En particular de cocaína. Un negocio ilegal que según estimaciones del Departamento de Estado de Estados Unidos reporta a los señores de la droga unos US$ 400 mil millones al año. Hay expertos que aseguran que esas estimaciones son modestas. El cultivo de la hoja de coca -materia prima del clorhidrato de cocaína y también de la hiperadictiva pasta base- se extiende de manera incesante en América Latina, particularmente en

x Alianzas de narcos llegan a Uruguay Drogas. Tras la caída de grupo mexicano amenazaron a jerarcas Extensión de cultivos de cocaína en Bolivia preocupa a autoridades En 9 meses incautaron más de 700 kilos plantados allí | Según un informe internacional sobre tácticas de países ¿Narcotraficantes mexicanos rescatados del Penal de Libertad en helicópteros? ¿Amenazas de muerte contra toda la cúpula del Ministerio del Interior? Una sombra que se alarga por todo el continente y finalmente llega a Uruguay. El fenómeno se llama "hiperproducción de drogas". En particular de cocaína. Un negocio ilegal que según estimaciones del Departamento de Estado de Estados Unidos reporta a los señores de la droga unos US$ 400 mil millones al año. Hay expertos que aseguran que esas estimaciones son modestas. El cultivo de la hoja de coca -materia prima del clorhidrato de cocaína y también de la hiperadictiva pasta base- se extiende de manera incesante en América Latina, particularmente en tres países: 32.000 hectáreas cultivadas en Bolivia; 55.000 en Perú y unas 90.000 en Colombia. La extensión de los cultivos en Bolivia es un fenómeno que preocupa, particularmente, a las autoridades uruguayas encargadas de reprimir el narcotráfico. Los más de 700 kilos de cocaína capturados entre agosto de 2007 y abril de 2008 en Uruguay procedían del país gobernado por Evo Morales. Un presidente ex cocalero y defensor del cultivo de la hoja de coca, política que -creen expertos antidrogas uruguayos- favorece los intereses de los narcotraficantes. Pero las amenazas reales del narcotráfico exceden a países vecinos. La caída en febrero de una organización de narcotraficantes mexicanos que habían llegado al país hacía ocho meses y ya habían construido una compleja fachada legal y comercial, puso en evidencia un dato inesperado: Uruguay es apetecido por algunos de los señores de la droga. A dos meses del encarcelamiento de los narcos mexicanos comienza a reinar la impaciencia. Una serie de mensajes anónimos con amenazas de muerte para toda la cúpula del Ministerio del Interior y, en particular, para la Dirección General de Represión al Tráfico Ilícito de Drogas (Dgrtid), trajo los primeros ecos del terror que los poderosos cárteles siembran al norte del continente. Advertencias no faltaron. A fines de 2007 el titular de la Dgrtid, Julio Guarteche, lo había dicho claramente: "Prevemos más tráfico de cocaína, y también prevemos más tráfico de pasta base". A principios de este mes la ministra del Interior, Daisy Tourné, había deslizado otra advertencia. Al referirse al contexto de alto riesgo que vive el Penal de Libertad durante su comparecencia en la comisión bicameral de seguimiento carcelario, dijo a los legisladores que podría suceder que se intentara el rescate en helicópteros de algunos de "estos señores de la droga". "LOS ZETAS". El rescate del jefe del Cártel del Golfo, Osiel Cárdenas, preso en la cárcel de máxima seguridad de Almoloya, en Juárez, fue planeado con el uso de helicópteros de alta tecnología. El plan que frustraron las autoridades mexicanas había sido elaborado por un grupo conocido como "Los Zetas". Este temible grupo mexicano está integrado por unos 200 ex militares de élite que comenzaron vendiendo servicios de protección y terminaron con un cliente único: el poderoso Cártel del Golfo. Tienen en su haber una extensa lista de asesinatos, secuestros y atentados. La atomización de los grandes cárteles de la droga, que viene enfrentando a grupos más pequeños en un interminable "unos contra otros", les dio a "los Zetas" un papel de privilegio. Los integrantes del grupo están especializados en el uso de armas bélicas de alto poder, saben realizar operaciones de inteligencia y han venido ensanchando su base con el reclutamiento de adolescentes: "los zetitas". Según una información difundida por el diario "El Mercurio" de Chile, los "Zetas" encaran ahora una nueva campaña de reclutamiento en el noreste de México. "Paren de sufrir, ex militares, PFP (policías federales) y soldados de Mérida, únete a las filas del cártel del Golfo", reza una pancarta hallada en la ciudad de Tampico. Su actuación está ampliamente documentada en territorio mexicano, pero no hay registro de actividades en otros países. CONTINENTE ROTO. Un reciente informe de "El País" de Madrid revelaba las divisiones que existen entre los gobiernos latinoamericanos ante el tema de las drogas. "Latinoamérica se rompe por la droga", es el título del reportaje que pinta un cuadro complejo. "El gobierno argentino se prepara para no perseguir penalmente a los consumidores, y Jamaica, el mayor productor de marihuana del Caribe, estudia legalizar la planta. Sobre la mesa está el nuevo dilema entre permisividad o tolerancia cero para abordar el problema de la droga", señala el artículo. El reportaje pone el foco sobre la discusión que se viene planteando en Argentina en torno a la despenalización del consumo de drogas. Aunque alude a Uruguay como un país inmerso en la misma polémica, cabe recordar que la legislación uruguaya no penaliza el consumo de estupefacientes sino su venta, producción e importación, así como actividades conexas al tráfico. "El anuncio hecho por Argentina ha causado una gran polémica en el país donde el 75% de la población se opone a la despenalización del consumo de drogas", apunta el informe periodístico. Hoja de coca: Cultivos de 32.000 hectáreas en Bolivia, 55.000 en Perú y 90.000 en Colombia. Políticas juegan a favor del tráfico El país de madrid Inefica- ces y contraproducentes. Con estas palabras define el International Crisis Group (ICG) las políticas seguidas en Estados Unidos, Europa y Latinoamérica contra el tráfico de drogas debido en gran parte a la descoordinación de las acciones, que "han ido funcionando a favor de las redes", según advierte Mark Schenider, vicepresidente de este think tank estadounidense. Pero hay algo mucho más preocupante. Según denuncia el ICG en su informe de 2008, la política de erradicación de hoja de coca "casi siempre está acompañada de violaciones a los derechos humanos". El organismo subraya que las fuerzas paramilitares que intervienen en las operaciones -la fumigación de los cultivos o la destrucción de las plantas desde el suelo- generan "movimientos antigubernamentales" en las zonas donde se practican. Un argumento en el que ahonda el Transnational Institute, con sede en Amsterdam: "Las fumigaciones aéreas ponen en marcha un círculo de destrucción humana, social y medioambiental que ha exacerbado los conflictos sociales en Colombia, Perú y Bolivia", señalan. Según el ICG están fracasando tanto las políticas de erradicación de los cultivos como la de frenar la demanda de consumo, especialmente en los tres grandes mercados mundiales: Estados Unidos, Europa y Brasil. "Es hora de cambiar de estrategia", advierte Schenider. Sin drama pero con cuidado Luego de que las amenazas a la cúpula del Ministerio del Interior tomaran estado público, su titular, Daisy Tourné llamó el viernes a quitarle dramatismo. Sostuvo que "es muy importante continuar adelante con la política del Ministerio en lo que es la lucha sin cortapisas al narcotráfico". El subsecretario Ricardo Bernal, por su parte, afirmó que se vienen realizando tareas de inteligencia e investigación para determinar si efectivamente hay un grupo de narcotraficantes dispuestos a atentar contra las jerarquías del Ministerio del Interior. "Estamos hablando de organizaciones muy poderosas, que pueden sentirse afectadas, de hecho lo están", aseguró. Si bien en un principio se creyó que las amenazas podrían provenir de organizaciones de Paraguay, ahora los servicios de inteligencia policial investigan la "conexión mexicana". Distintas fuentes de la cartera señalaron que uno de los poderosos carteles de ese país podrían estar tras los mensajes. Por otra parte el Sindicato de Policías manifestó su apoyo a Interior ante las "reprobables" amenazas. `No salgas a la calle sin`


In [36]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto No salgas a la calle sin
pattern = r"No salgas a la calle sin"
results = re.findall(pattern, str_text)
print(len(results))

# cantidad de ocurrencias con texto No salgas a la calle sin y salto de linea
pattern_1 = r"No salgas a la calle sin\n"
results_1 = re.findall(pattern_1, str_text)
print(len(results_1))

pattern_3 = r"No salgas a la calle sin saber de qué se habla..."
results_3 = re.findall(pattern_3, str_text)
print(len(results_3))

pattern_4 = r"No salgas a la calle sin ver más► saber de qué se habla"
results_4 = re.findall(pattern_4, str_text)
print(len(results_4))

print(len(results_1) + len(results_3) + len(results_4))



4917
4235
0
0
4235


#### Solucion


In [37]:
testing_str = lines[14903]

replace_pattern = r"No salgas a la calle sin\n"
result = re.sub(replace_pattern, '', testing_str)  

replace_pattern = r"No salgas a la calle sin saber de qué se habla..."
result = re.sub(replace_pattern, '', result)

replace_pattern = r"No salgas a la calle sin ver más► saber de qué se habla"

result = re.sub(replace_pattern, '', result)
print(result)

x Alianzas de narcos llegan a Uruguay Drogas. Tras la caída de grupo mexicano amenazaron a jerarcas Extensión de cultivos de cocaína en Bolivia preocupa a autoridades En 9 meses incautaron más de 700 kilos plantados allí | Según un informe internacional sobre tácticas de países ¿Narcotraficantes mexicanos rescatados del Penal de Libertad en helicópteros? ¿Amenazas de muerte contra toda la cúpula del Ministerio del Interior? Una sombra que se alarga por todo el continente y finalmente llega a Uruguay. El fenómeno se llama "hiperproducción de drogas". En particular de cocaína. Un negocio ilegal que según estimaciones del Departamento de Estado de Estados Unidos reporta a los señores de la droga unos US$ 400 mil millones al año. Hay expertos que aseguran que esas estimaciones son modestas. El cultivo de la hoja de coca -materia prima del clorhidrato de cocaína y también de la hiperadictiva pasta base- se extiende de manera incesante en América Latina, particularmente en

In [38]:
str_text = auxiliar_full_lines

# analisis de recorrer todo el texto
replace_pattern = r"No salgas a la calle sin\n"
result = re.sub(replace_pattern, '', str_text)  

replace_pattern = r"No salgas a la calle sin saber de qué se habla..."
result = re.sub(replace_pattern, '', result)

replace_pattern = r"No salgas a la calle sin ver más► saber de qué se habla"
total_result = re.sub(replace_pattern, '', result)  

# cantidad de ocurrencias con texto -No salgas a la calle sin-
pattern = r"No salgas a la calle sin"
results = re.findall(pattern, total_result)
print(len(results))

682


### Texto "¿Te interesa esta noticia?" en el inicio


In [39]:
print(lines[25015])


"Jaque" al fideicomiso en garantía ¿Te interesa esta noticia?     LORENA JONES Hace unos días se dio a conocer la tan esperada sentencia del Juzgado Letrado de Concursos de 1o turno que puso fin al incidente generado por la rescisión del contrato de fideicomiso que vinculaba a Paylana S.A. con el Banco de la República (BROU). La decisión judicial ha provocado diversas reacciones. En el ámbito académico, la cátedra se encuentra dividida en cuanto a este asunto pero, sin lugar a dudas, el fallo no es compartido por las instituciones que se encuentran en una situación semejante, temerosas de perder sus garantías fiduciarias, tal como sucedió con el BROU en el caso que nos compete en la columna de hoy. CONCEPTO. El fideicomiso en garantía es un negocio por el cual el deudor de una obligación, transfiere bienes o derechos propios a favor de un patrimonio de afectación administrado por un fiduciario, con el encargo que, al vencimiento de las obligaciones garantizadas y en caso 

"Jaque" al fideicomiso en garantía `¿Te interesa esta noticia?`     LORENA JONES Hace unos días se dio a conocer la tan esperada sentencia del Juzgado Letrado de Concursos de 1o turno que puso fin al incidente generado por la rescisión del contrato de fideicomiso que vinculaba a Paylana S.A. con el Banco de la República (BROU). La decisión judicial ha provocado diversas reacciones. En el ámbito académico, la cátedra se encuentra dividida en cuanto a este asunto pero, sin lugar a dudas, el fallo no es compartido por las instituciones que se encuentran en una situación semejante, temerosas de perder sus garantías fiduciarias, tal como sucedió con el BROU en el caso que nos compete en la columna de hoy. CONCEPTO. El fideicomiso en garantía es un negocio por el cual el deudor de una obligación, transfiere bienes o derechos propios a favor de un patrimonio de afectación administrado por un fiduciario, con el encargo que, al vencimiento de las obligaciones garantizadas y en caso de incumplimiento, el fiduciario realice el patrimonio afectado en garantía y con el producido cancele el pasivo. Cuando el beneficiario de un fideicomiso en garantía es una institución de intermediación financiera, como en este caso el BROU, la ley autoriza que el Banco sea al mismo tiempo beneficiario -acreedor- y fiduciario. En cuanto a las ventajas del fideicomiso en garantía, la doctrina señala su mayor flexibilidad y celeridad derivada de la ejecución extrajudicial de los bienes, lo que lo distingue de otros instrumentos de garantía como la hipoteca. En teoría, o al menos hasta ahora, resultaba una garantía jurídica segura y eficaz para el acreedor. La empresa sanducera Paylana mantiene una deuda con el BROU por US$ 21 millones, la cual fue parcialmente garantizada mediante un fideicomiso en garantía, constituido sobre los créditos presentes y futuros a favor de la empresa textil. NORMATIVA. La normativa aplicable en este caso es la reciente ley 18.387 (2008) que regula la declaración judicial del concurso y la reorganización empresarial, cuyo énfasis está puesto en la supervivencia de las unidades productivas económicamente viables, así como la eficiente y equitativa liquidación de las que no lo sean. Dicha ley incluye en su artículo 68 la posibilidad de rescindir unilateralmente por el síndico o el deudor con autorización del interventor, determinados contratos celebrados por el deudor con anterioridad a la apertura del concurso. El inciso primero del artículo establece: "Art. 68. (Contratos pendientes de ejecución). En caso de existir a la fecha de declaración del concurso, contratos de los cuales deriven obligaciones del deudor pendientes de ejecución, se procederá de la forma siguiente: 1. El síndico o el deudor con la autorización del interventor, tendrán la facultad de rescindir unilateralmente el contrato, notificando este hecho a la contraparte, dentro del plazo establecido para que los acreedores presenten la solicitud de reconocimiento de sus créditos". La ley permite a la administración concursal interrumpir el cumplimiento de los "contratos de los cuales deriven obligaciones del deudor pendientes de ejecución", cuando entienda que estos no generan un beneficio a la masa. La pregunta es: ¿el fideicomiso en garantía puede ser alcanzado por esta norma? EL CASO. Paylana S.A. al amparo del art. 68 de la ley 18.387 y autorizada por la intervención, promovió la rescisión del contrato de fideicomiso en garantía celebrado el 5 de mayo de 2010 a favor el BROU. El BROU se opuso sosteniendo que no existían obligaciones pendientes de cumplimiento, por cuanto se trata de un contrato de cumplimiento instantáneo cuya obligación principal es la constitución del patrimonio de afectación. Paylana sostiene que existen obligaciones pendientes de ejecución y reclama la devolución de los créditos por ventas que se hayan transferido a favor del BROU en virtud del contrato rescindido. El reciente fallo judicial declaró que los requisitos exigidos por la ley 18.387 se verifican en el caso, señalando que la norma no distingue entre diferentes tipos de contratos y de obligaciones pendientes de ejecución. Según la sentencia, los requisitos exigibles en forma acumulativa son: 1. que exista uno o más contratos de los cuales deriven obligaciones a cargo del deudor concursado, y 2. que dichas obligaciones se encuentren pendientes de ejecución a la fecha de declaración del concurso. Conforme surge del fallo, se trata de una norma de excepción que desequilibra el régimen general de las obligaciones y por consiguiente de interpretación estricta. En definitiva, el Juzgado de Concursos falló a favor de rescindir parcialmente el fideicomiso que el BROU tenía con la textil, entendiendo que en el caso existen obligaciones pendientes de ejecución a cargo de Paylana, lo que implica que el banco se transforme en un acreedor quirografario -sin garantía- sumándose a la lista de acreedores de la empresa. El fallo consideró que las obligaciones de pago de los gastos y honorarios extraordinarios derivados de la gestión y administración de los bienes así como el pago por concepto de comisiones fiduciarias que Paylana debía abonar al BROU, conforme a lo pactado en el contrato de fideicomiso, constituyen las obligaciones pendientes de ejecución que exige el legislador. Es compartible la opinión de la Sede en cuanto a la existencia de obligaciones pendientes de ejecución por parte del deudor, pero no se puede desconocer que dichas obligaciones son instrumentales respecto a las obligaciones principales del contrato de garantía. El eje de la discusión consiste en determinar si la trascendencia de las referidas obligaciones accesorias, justifican la rescisión del fideicomiso. INTERPRETACIONES. Para quienes no comparten la sentencia resulta evidente que el espíritu y finalidad de esta norma -ratio legis- no responde a este tipo de negocios jurídicos de garantía. Parece claro, que la norma fue prevista para otro tipo de situaciones, por ejemplo, un contrato de suministro o de arrendamiento a largo plazo, que implique una carga negativa para la masa de acreedores y para la propia continuidad de la empresa. Una interpretación teleológica o finalista de la norma no permitiría incluir este tipo de negocios de garantía dentro de los contratos alcanzados por el derecho potestativo de rescisión consagrado en la ley 18.387. En cambio, una interpretación esclava del texto de la ley no permite distinguir al intérprete donde el legislador no lo hizo. Postura a la que parece haberse afiliado el fallo de primera instancia. Nos preguntamos si el BROU hubiese renunciado al cobro de las obligaciones pendientes de cumplimiento -gastos, honorarios y comisiones- ¿habría conservado su garantía? Creemos que sí, e indudablemente tal situación sería mucho más beneficiosa para el BROU. Se encuentran enfrentados, por un lado, el interés por la recomposición de los activos que va de la mano con la continuidad de la empresa y por otro, la tutela de los derechos de los acreedores garantizados mediante contratos de fideicomiso que perderían la seguridad que hasta ahora les brindaba ese contrato. Las consecuencias económicas que el fallo acarrearía a los bancos, no pueden ser ajenas a la hora de analizar el fondo del asunto y eventualmente de una reforma legislativa. CONSECUENCIAS. Es razonable pensar que disminuirá sensiblemente la confianza en este tipo de negocio de garantía, el que dejaría de utilizarse, pero además tendría un efecto devastador respecto de los fideicomisos en garantía ya celebrados. ¿Qué deben hacer los bancos? ¿Qué hará el BCU? ¿Deberán recalificar los créditos y previsionarlos conforme a los nuevos riesgos? ¿Qué banco puede estar a salvo de que su deudor entre en concurso? No se puede dejar de reconocer, siguiendo la más prestigiosa doctrina, que la vulneración de la eficacia del fideicomiso en garantía representa una grave lesión a la posibilidad de acceso al crédito de los operadores económicos. En los próximos días se pronunciará el Tribunal de Apelaciones. De todas formas, sería conveniente que un tema tan sensible y trascendente para la actividad empresarial y bancaria sea resuelto definitivamente por el Poder Legislativo, despejando la incertidumbre que pueden generar las distintas interpretaciones judiciales.


In [40]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto ¿Te interesa esta noticia?
pattern = r"\¿Te interesa esta noticia\?"
results = re.findall(pattern, str_text)
print(len(results))

# cantidad de ocurrencias con texto Te interesa esta noticia - sin signos de pregunta
pattern_1 = r"Te interesa esta noticia"
results_1 = re.findall(pattern_1, str_text)
print(len(results_1))

# cantidad de ocurrencias con texto Te interesa esta noticia? - sin signos de pregunta
pattern_2 = r"\¿?Te interesa esta noticia\?"
results_2 = re.findall(pattern_2, str_text)
print(len(results_1))

# cantidad de ocurrencias con texto Te interesa esta noticia? - sin signos de pregunta
pattern_3 = r"[^¿]Te interesa esta noticia?"
results_3 = re.findall(pattern_3, str_text)
print(len(results_3))

# CONCLUSION:
# No siempre ocurre en el inicio
# no siempre arranca con el simbolo ¿

10034
10079
10079
45


#### Solucion

In [41]:
# REEMPLAZO:
testing_str = lines[25015]

replace_pattern = r"\¿?Te interesa esta noticia\?"
result = re.sub(replace_pattern, '', testing_str)  
print(result)
print('')

# cantidad de ocurrencias con texto -¿Te interesa esta noticia?-
pattern = r"\¿?Te interesa esta noticia\?"
results = re.findall(pattern, total_result)

"Jaque" al fideicomiso en garantía      LORENA JONES Hace unos días se dio a conocer la tan esperada sentencia del Juzgado Letrado de Concursos de 1o turno que puso fin al incidente generado por la rescisión del contrato de fideicomiso que vinculaba a Paylana S.A. con el Banco de la República (BROU). La decisión judicial ha provocado diversas reacciones. En el ámbito académico, la cátedra se encuentra dividida en cuanto a este asunto pero, sin lugar a dudas, el fallo no es compartido por las instituciones que se encuentran en una situación semejante, temerosas de perder sus garantías fiduciarias, tal como sucedió con el BROU en el caso que nos compete en la columna de hoy. CONCEPTO. El fideicomiso en garantía es un negocio por el cual el deudor de una obligación, transfiere bienes o derechos propios a favor de un patrimonio de afectación administrado por un fiduciario, con el encargo que, al vencimiento de las obligaciones garantizadas y en caso de incumplimiento, el fidu

In [42]:
str_text = auxiliar_full_lines

# analisis de recorrer todo el texto
replace_pattern = r"\¿?Te interesa esta noticia\?"
results = re.findall(pattern, str_text)
print(f'Antes - {len(results)}')

text_result = re.sub(replace_pattern, '', str_text)  
results = re.findall(pattern, text_result)
print(f'Despues - {len(results)}')


Antes - 10079
Despues - 0


### Correos


**NOTAR QUE ADEMAS, EL TEXTO ES UN JUEGO DE CRUCIGRAMA**

In [43]:
print(lines[82])

Rincón de juegos Por Leonardo Conde, especial para EL PAIS CondeLeonardo@netscape.net HORIZONTALES 1) Cruel, refinada y pervertida. 7) Emplear el dinero en alguna cosa. 13) Levantan, alzan. 14) Acicalado, pulcro, limpio. 15) Zumaque, arbusto. 16) Cuero curtido de modo que conserve su pelo natural. 18) Tercer día del mes. 19) Rey de Tebas, que dio muerte a su padre y luego se casó con su propia madre. 21) Iglesia catedral. 23) Esposa de Joaquín, madre de María. 24) Santo, si no es Domingo, Tomás o Toribio. 25) Halago o adulación fingidos. 27) Cama portátil plegable. 29) Empleo. 33) Parte coloreada del ojo que rodea la pupila. 34) Cerveza ligera inglesa. 35) Muesca de guía que tienen los tipos de imprenta. 36) Halo, disco luminoso que suele ponerse detrás de la cabeza de las imágenes de santos. 38) Mazo para romper piedras, almádena. 39) Sujetapapeles de alambre. 40) Yerno de Mahoma. 41) Pandero ceremonial de los árabes. 44) Adverbio de modo. 45) Vaso antiguo, en forma de cu

Rincón de juegos Por Leonardo Conde, especial para EL PAIS `CondeLeonardo@netscape.net` HORIZONTALES 1) Cruel, refinada y pervertida. 7) Emplear el dinero en alguna cosa. 13) Levantan, alzan. 14) Acicalado, pulcro, limpio. 15) Zumaque, arbusto. 16) Cuero curtido de modo que conserve su pelo natural. 18) Tercer día del mes. 19) Rey de Tebas, que dio muerte a su padre y luego se casó con su propia madre. 21) Iglesia catedral. 23) Esposa de Joaquín, madre de María. 24) Santo, si no es Domingo, Tomás o Toribio. 25) Halago o adulación fingidos. 27) Cama portátil plegable. 29) Empleo. 33) Parte coloreada del ojo que rodea la pupila. 34) Cerveza ligera inglesa. 35) Muesca de guía que tienen los tipos de imprenta. 36) Halo, disco luminoso que suele ponerse detrás de la cabeza de las imágenes de santos. 38) Mazo para romper piedras, almádena. 39) Sujetapapeles de alambre. 40) Yerno de Mahoma. 41) Pandero ceremonial de los árabes. 44) Adverbio de modo. 45) Vaso antiguo, en forma de cuerno o de cabeza de animal, usado en los banquetes. 48) Ijada. 50) Letra griega. 52) Azuela, herramienta de carpintero. 53) Ciudad cuyas murallas se derrumbaron al sonar las trompetas de sus sitiadores. 55) Van a donde los llaman o necesitan. 57) Posturas del yoga. 58) Diosa griega, madre de Artemisa y Apolo. VERTICALES: 1) Jorge ..., recordado arquero de Nacional, campeón del mundo con los tricolores. 2) Avalancha de nieve. 3) Apartarse, abandonar una empresa o intento ya iniciado o proyectado. 4) Cuatro en el circo romano. 5) De Niro, en "Los Intocables". 6) Ave trepadora americana. 7) El que remaba forzado en las galeras. 8) Moneda romana de bronce. 9) Hermano menor de Caín. 10) Nombre de la plantación de Scarlett O`Hara. 11) Antiguo protectorado británico en el extremo SO de Arabia (actual Yemen). 12) Flor del azafrán. 17) Dios de la Medicina, hijo de Apolo. 20) Unidad para medir distancias interestelares. 22) Cinturón de seda del kimono. 26) Hidróxido metálico que actúa como base fuerte. 27) Famosa sigla de los servicios secretos norteamericanos. 28) Archipiélago de Indonesia. 30) Enfadado, iracundo, enojado. 31) Pedro, Iván o Nicolás. 32) Indio fueguino. 34) Vientos fijos que soplan de la zona tórrida, con inclinación al nordeste o al sudeste, según el hemisferio. 37) Onda marina. 38) Instrumento musical que consiste en una calabaza con granos de maíz o piedritas en su interior. 41) Astil de la llave, entre el ojo y el paletón. 42) Achaques, dolencias habituales de la vejez. 43) Extraña, poco frecuente, como algunas tierras. 46) Aguardiente anisado y muy dulce. 47) Canción de cuna. 49) Río de Alemania. 51) Semejante, parecido. 54) Calcio. 56) Do, pero hace mucho tiempo.  Utilidades


#### Casos con el texto "Boris Cristoff" - son horoscopos- considero que deberian eliminarse

In [45]:
auxiliar_lines = lines
print(len(auxiliar_lines))

res = [line for line in auxiliar_lines if 'Boris Cristoff' in line]
print(len(res))
regex =  r"Boris Cristoff .*?Digital\n"
res_2 = [line for line in auxiliar_lines if re.search(regex, line)]
print(len(res_2))

120692
155
142


In [46]:
auxiliar_lines = lines
print(len(auxiliar_lines))

regex =  r"Boris Cristoff .*?Digital\n"

resulting_lines = list(filter(lambda line: not(re.search(regex, line)), auxiliar_lines))
len(resulting_lines)

120692


120550

Hay una noticia que habla de boris cristoff

In [47]:
lines[80779]

'boris cristoff revela sus predicciones sobre el futuro del uruguay y el mundo "El presidente Bush está en peligro" Boris Cristoff presidirá el Primer Congreso Uruguayo de Astrología que tendrá lugar el 7 y 8 de octubre. Entre las predicciones que se harán en el evento, Cristoff destacó el inminente peligro de muerte de Bush y la persistencia de los conflictos por las plantas de celulosa. POR | PABLO PERA PIROTTO Boris Cristoff nunca se queda quieto. A los 81 años tiene las energías de una persona joven y muchas ganas de seguir profundizando en el conocimiento de los astros y su influencia en las personas, algo a lo que ha dedicado más de cuarenta años de su vida. Publica desde hace años el horóscopo en forma diaria, escribe libros que son best sellers, atiende a quienes quieran conocer su destino y, como si fuera poco, ahora está organizando el Primer Congreso Uruguayo de Astrología, en donde promete que se divulgarán predicciones que darán que hablar. -¿Qué temas se 

#### Textos con el correo CondeLeonardo@netscape.net Y CondeLeonardo@aol.com son crucigramas de Leonardo Conde

In [48]:
auxiliar_lines = lines
print(len(auxiliar_lines))

regex =  r"CondeLeonardo@netscape.net"

searching = [line for line in auxiliar_lines if re.search(regex, line, re.IGNORECASE)]
print(len(searching))

resulting_lines = list(filter(lambda line: not(re.search(regex, line, re.IGNORECASE)), auxiliar_lines))
len(resulting_lines)

120692
733


119959

#### Analisis de correos

In [49]:
str_text = auxiliar_full_lines

regex = r'..................\| \b[\w.-]+?@\w+?\.\w+?\b......'
results = re.findall(regex,str_text) 

results = [line for line in results if not('CondeLeonardo@netscape.net' in line)]
results = [line for line in results if not('CondeLeonardo@aol.com' in line)]
results = [line for line in results if not('cristoff@adinet.com.uy' in line)]

print(len(results))
for find in results[:100]:
  print(find)

544
ng Martín Colombo | mcolombo@ferrere.comvie nov 8
OR Gabriela Rocha | grocha@elpais.com.uy El
ia Martín Fridman | mfridman@ferrere.comvie nov 1
OR GABRIELA ROCHA | GROCHA@ELPAIS.COM.UY Ha
laudio Destéfano* | claudio@bizers.com.ar El
OR Silvana Nicola | snicola@elpais.com.uy Co
ella Maris Pusino | spusino@elpais.com.uy In
 Antonio Larronda | alarronda@elpais.com.uy Ya
DOLFO M. IRIGOYEN | romairigoyen@adinet.com.uy En
POR Mariana Goday | mgoday@elpais.com.uy Ll
or Diego Ferreira | dferreira@elpais.com.uy Ax
os GABRIELA ROCHA | grocha@elpais.com.uy La
POR Mariana Goday | mgoday@elpais.com.uy Si
QUÍN SECCO GARCÍA | josecco@yahoo.com En lo
OR GASTÓN PÉRGOLA | gpergola@elpais.com.uy ¿C
or Silvana Nicola | snicola@elpais.com.uy Ca
or Diego Ferreira | dferreira@elpais.com.uy So
CIAL PARA EL PAIS | CONDELEONARDO@NETSCAPE.NET Estam
OR DIEGO FERREIRA | dferreira@elpais.com.uy In
R Sebastián Panzl | spanzl@elpais.com.uy Tr
 IGNACIO QUARTINO | iquartino@elpais.com.uy El
Laura V. Meléndez | lmel

In [50]:
from enum import unique
str_text = auxiliar_full_lines

regex = r'\b[\w.-]+?@\w+?\.\w+?\b'
all_emails = re.findall(regex,str_text) 

print(f"Total emails: {len(all_emails)}")
# for find in all_emails[:20]:
#   print(find)

unique_emails = list(set(all_emails))
print(f"distinct emails: {len(unique_emails)}")
# for find in unique_emails[:20]:
#   print(find)

counter = {}
for email in unique_emails:
  counter[email] = all_emails.count(email)
print(counter)

Total emails: 3045
distinct emails: 791
{'fliadicbo@hotmail.com': 1, 'yuri.lopezfarias@hotmail.com': 1, 'cultura@ucu.edu': 1, 'culturapop@um.edu': 1, 'redjuez@gmail.com': 1, 'barialrius@yahoo.com': 4, 'consulado@uruguaymiami.org': 3, 'centropiazzolla@hotmail.com': 1, 'spapostolo@cultura.com': 1, 'luis10_624@hotmail.com': 1, 'arquiferblanco1@msn.com': 1, 'paularsvp@elpais.com': 1, 'tar132002@hotmail.com': 1, 'romairigoyen@hotmail.com': 1, 'djcarlitos@microsoft.com': 1, 'info@anv.gub': 1, 'icau@mec.gub': 1, 'teijeiro@adinet.com': 1, 'eventos@hoteldelprado.com': 1, 'fesur@fesur.org': 1, 'angelo91234@aol.com': 1, 'cedres@zipmail.com': 1, 'mlecuona@ferrere.com': 1, 'loopez@adinet.com': 1, 'mdacosta@ferrere.com': 1, 'Cafferamcaffera@ferrere.comvie': 1, 'braford@adinet.com': 1, 'proyectofelisberto2013@gmail.com': 2, 'caballeroazul06@hotmail.com': 1, 'prensa@bocajuniors.com': 1, 'materos_g@libero.it': 1, 'ofecavero@hotmail.com': 1, 'Info@daresrecibir.org': 1, 'Claudio@bizers.com': 1, 'a.mejaie

In [51]:
import pandas as pd

a = pd.DataFrame.from_dict(counter, orient='index')
print(a.describe())
a.columns = ['quantity']
a = a.sort_values(by='quantity')
a

# parece que los emails mas repetidos son autores de noticias

                0
count  791.000000
mean     3.849558
std     28.579294
min      1.000000
25%      1.000000
50%      1.000000
75%      1.000000
max    724.000000


quantity
fliadicbo@hotmail.com                          1
ServicioDomésticoNoPresentismo@bps.gub         1
info@uy.jumpingclay                            1
ritahay@hotmail.com                            1
vidal.maru@gmail.com                           1
...                                          ...
mgoday@elpais.com                            104
grocha@elpais.com                            109
dferreira@elpais.com                         158
barilarius@yahoo.com                         206
CondeLeonardo@netscape.net                   724

[791 rows x 1 columns]

In [57]:
a[765:]

quantity
digital@elpais.com                 9
mcastaldi@elpais.com               9
romairigoyen@gmail.com            10
jcraffo@elpais.com                11
info@opcion.com                   13
vdiaz@elpais.com                  14
pjimenez@seragro.com              20
lmelendez@elpais.com              25
nlussich@seragro.com              31
claudio@bizers.com                34
CondeLeonardo@aol.com             36
gpergola@elpais.com               40
qpasa@elpais.com                  42
jchouy@seragro.com                43
spanzl@elpais.com                 48
alarronda@elpais.com              48
elpepepregunton@gmail.com         59
cristoff@adinet.com               59
barilari@laraza.com               77
spusino@elpais.com                78
snicola@elpais.com                83
mgoday@elpais.com                104
grocha@elpais.com                109
dferreira@elpais.com             158
barilarius@yahoo.com             206
CondeLeonardo@netscape.net       724

In [52]:
str_text = auxiliar_full_lines

regex = r'..........................Tel: 1950 7177. Museo de Historia del Arte .*? \b[\w.-]+?@\w+?\.\w+?\b....................'
results = re.findall(regex,str_text) 

print(len(results))
for find in results[:50]:
  print(find)

KeyboardInterrupt: 

### Autor del articulo


In [58]:
testing_str = lines[64557]


regex = r'Por .*? \|'
results = re.findall(regex,testing_str) 

print(f'Antes - {len(results)}')
results

Antes - 1


['Por Gastón Pérgola |']

In [59]:
testing_str[:200]

'Golazos publicitarios de Schneck y Ancel Las campañas encabezadas por "El Loco" y Gorzy presagiaron lo imprevisible   Por Gastón Pérgola | gpergola@elpais.com.uy Ancel y Schneck no le pueden pedir '

In [60]:
testing_str = lines[64557]


regex = r'\b[\w.-]+?@\w+?\.\w+?\b'
results = re.findall(regex,testing_str) 

print(f'Antes - {len(results)}')
results

Antes - 1


['gpergola@elpais.com']

Golazos publicitarios de Schneck y Ancel Las campañas encabezadas por "El Loco" y Gorzy presagiaron lo imprevisible   `Por Gastón Pérgola | gpergola@elpais.com.uy` Ancel y Schneck no le pueden pedir más a las apuestas publicitarias que realizaron con el "Loco" Sebastián Abreu y Sergio Gorzy. Por si sus premonitorios avisos hubiesen sido poco, el periodista como maestro de ceremonia y el futbolista como improvisado conductor se robaron la cámara el martes pasado durante el homenaje a la selección de fútbol en las afueras del Palacio Legisltativo. Ambas marcas, cada una a su manera, apostó con estrategias creativas a la selección uruguaya -a través de estos dos personajes- y las propuestas terminaron siendo casi un presagio de lo que fue la realidad de Uruguay en la Copa del Mundo. Sergio Gorzy, el periodista deportivo devenido en fanático insufrible del combinado celeste, que desde hace casi una década viene pronosticando a Uruguay campeón del mundo, se convirtió tres meses antes del mundial en la cara visible de una promoción de Schneck, que alentaba la idea de que "Los últimos pueden ser los primeros" (en alusión a que la celeste fue la última en clasificar a la Copa) e insistía con que se estaba a "sólo siete partidos de ser campeones del mundo". Por su parte, Ancel, el día del partido inagural del mundial, salió con una campaña de tono institucional que tenía como principal protagonista a Abreu y su loca forma de patear los penales, "picando" la pelota. Terminó el mundial y la realidad superó a la ficción (publicitaria): el "Loco", con pocos minutos en cancha, tuvo su oportunidad y la volvió a picar en épica definición por penales, al tiempo que Uruguay quedó a un partido de la final del mundo, una idea que solo Schneck y Gorzy se animaron a aventurar. Estas apuestas, que a priori podrían haber sido un laberinto sin salida para las marcas, terminaron dando sus réditos, con un efecto multiplicador sobre la recordación del aviso publicitario y de las propias firmas. Tan es así que, según un sondeo de tendencias sobre el comportamiento de los hinchas uruguayos durante el mundial realizado por Mediaedge:cia, Ancel fue la única marca uruguaya entre las cinco más recordadas que pautaron durante la Copa, acompañada por Coca Cola, McDonald's, Adidas y Sony. En promociones asociadas al mundial aparecen, por orden de recordación, Schneck (Los últimos serán los primeros); Coca-Cola (ver el mundial en Moviecenter y Promo Vasos); Pilsen (Viaje a Sudáfrica en Motorhome), Halls (Respirá Sudáfrica) y Mc Donald's (Corazonadas). a dos partidos Un relevamiento de mercado le arrojó a Schneck que si bien la marca es líder en varias de las categorías en las que está presente, debía fortalecer la asociación de marca en el rubro hamburguesas. Fue así que vieron oportuno aprovechar la ocasión del mundial para lanzar una promoción. "Resulta que habíamos sido los últimos, literalmente, en clasificar al mundial, y se nos ocurrió la idea justamente de jugar con ese concepto", explicó Roberto Lafluf, principal de la agencia Avisa, que se encarga de la comunicación del frigorífico. Entonces crearon una promoción en la que se elegía a once participantes (entre un total de 50.000 personas que se inscribieron) y de los seleccionados, el último en salir sorteado se llevaba el premio mayor: una excursión a Sudáfrica para dos personas. "Sobre ese desarrollo de campaña nos preguntamos quién podía defender este proceso de los últimos serán los primeros y ahí fue que surgió la figura de Sergio Gorzy. Le planteamos la idea y le encantó. El protagonista calzaba en todos sus puntos", cuenta el publicista. Mediante una serie de spots publicitarios previos al mundial (en televisión, radio y vía pública) Gorzy anunciaba que Uruguay estaba a siete partidos de salir campeón, aventuraba cómo saldría Uruguay en la fase de grupos (coincidiendo con el resultado que finalmente se dió), arengaba un feriado nacional para cuando llegara la selección y hasta elaboró un recorrido para la caravana de bienvenida a los jugadores. "Estábamos muy jugados a lo que pasara. Pero teníamos algo claro. En una conversación con Sergio vimos que, de alguna forma, esta campaña lo ayudaba a convalidar su locura porque se tomó graciosamente y a la marca nadie le iba a caer si a la selección le iba mal. Nuestra protección, de alguna forma, era Gorzy que se hacía cargo de lo que decía", afirmó Lafluf. Pero los resultados empezaron a acompañar y la comunicación, que tenía fin al inicio del mundial, tuvo que seguir desarrollándose. "Los resultados increíblemente se dieron y ahí decidimos revivir su profecía", comenta el publicista. "Creo que además de lograr los objetivos de Schneck también reposicionamos la imagen de Gorzy", dice Lafluf a las risas. Y LA PICÓ NO MÁS Aunque Ancel ya venía realizando acciones publicitarias como sponsor oficial de la selección, la apuesta a Abreu tenía como objetivo asociar la marca a una figura fuerte de la selección, más aún teniendo en cuenta la apuesta de Claro al capitán Diego Lugano y de Movistar con Diego Forlán. Se pensó en Abreu e inmediatamente se hizo un estudio pormenorizado del jugador, que abarcó desde rasgos de su personalidad (la sencillez y desfachatez) hasta su estilo de juego, del que rescataron una de sus cualidades: la forma de patear los penales. "Salió redondito", dice ahora Fernando De Clemente, de Ginkgo, cuando Abreu la volvió a picar contra Ghana y todos hablaron de su publicidad. A varias Puntas vv Varios fueron los intentos de otras marcas por "pegarse" a la selección al ver cómo avanzaba en la copa. No todos tuvieron el éxito desado. Ottonello hizo una movida en Facebook para llevar al "Piñe" a ver la semifinal de Uruguay; hoy varios grupos de la red social lo califican de yeta. 50.000 personas participaron de la promoción mundialista de Schneck y la venta de sus hamburguesas creció 25%. Como yapa la promoción figura entre las más recordadas por el público. vv A pesar del optimismo de Schneck con Sergio Gorzy a la cabeza, la agencia que diseñó la estrategia, Avisa, tenía un plan de contingencia para un fracaso de Uruguay. Una alternativa era Gorzy arengando una revancha en Brasil 2014, tierra donde el último campeón fue la Celeste. Uruguay con más clicks en Google La búsqueda de Uruguay en Google (bajo las palabras clave Forlán y Uruguay) creció notablemente a nivel global a medida que la selección iba avanzando en la copa, según un relevamiento realizado por Mediaedge:cia, a través del Google Trends. Por ejemplo, comparado los cuatro semifinalistas a nivel global Uruguay fue la palabra más buscada el día dos de julio (fecha del partido contra Ghana) llegando al pico más alto de los últimos treinta días en comparación con las búsquedas realizadas a los otros 3 semifinalistas. A esa fecha le seguía Alemania (bajo la palabra Germany), el día de la goleada frente a Inglaterra por octavos de final y España (bajo la palabra Spain) cuando perdió con Suiza.


#### Solucion

In [61]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto -AUTOR-

pattern = r"Por \w* \w* \| "
results = re.findall(pattern, str_text)
print(len(results))
print(results[:20])

# cuantos autores distintos hay
distinct = list(set(results))
print(len(distinct))
print(distinct)

pattern = r"........Por \w* \w* \| ......."
results = re.findall(pattern, str_text)
print(len(results))
print(results[:20])

# Conclusion: hay casos donde tengo que agregar un "." y otros no son necesarios

241
['Por Roberto Cardellino | ', 'Por Leonardo Conde | ', 'Por Leonardo Conde | ', 'Por Leonardo Conde | ', 'Por Mariana Hill | ', 'Por Leonardo Conde | ', 'Por Antonio Larronda | ', 'Por Diego Ferreira | ', 'Por Roberto Cardellino | ', 'Por Silvana Nicola | ', 'Por Diego Ferreira | ', 'Por Nicolás Lussich | ', 'Por Leonardo Conde | ', 'Por Nicolás Lussich | ', 'Por Leonardo Conde | ', 'Por Diego Ferreira | ', 'Por Leonardo Conde | ', 'Por Leonardo Conde | ', 'Por Leonardo Conde | ', 'Por Mariana Goday | ']
37
['Por silvana nicola | ', 'Por Mariana Hill | ', 'Por Gabriela Rocha | ', 'Por Jorge Chouy | ', 'Por Natalia Trzenko | ', 'Por Malena Castaldi | ', 'Por GABRIELA BADE | ', 'Por Sebastián Panzl | ', 'Por DAVID GÓMEZ | ', 'Por Nicolás Lussich | ', 'Por Héctor Luna | ', 'Por Gabriela Cortizas | ', 'Por Greg Frost | ', 'Por Diego Ferreira | ', 'Por Gastón Pérgola | ', 'Por Mariana Goday | ', 'Por Craig Fagan | ', 'Por Silvana Nicola | ', 'Por Leonardo Conde | ', 'Por Victoria molnar

In [62]:
text = sanitice_text(lines[64557])
print('ANTES')
print(text)

replace_pattern = r"(\w)(\s*Por \w* \w* \|)"
text = re.sub(replace_pattern, r'\1.', text, re.IGNORECASE)

replace_pattern = r"\s*Por \w* \w* \|"
text = re.sub(replace_pattern, '', text, 0, re.IGNORECASE)

print('DESPUES')
print(text)

text = sanitice_text(lines[21151])
print('ANTES')
print(text)

replace_pattern = r"(\w)(\s*Por \w* \w* \|)"
text = re.sub(replace_pattern, r'\1.', text, re.IGNORECASE)

replace_pattern = r"\s*Por \w* \w* \|"
text = re.sub(replace_pattern, '', text, 0, re.IGNORECASE)

print('DESPUES')
print(text)

ANTES
Golazos publicitarios de Schneck y Ancel Las campanas encabezadas por "El Loco" y Gorzy presagiaron lo imprevisible   Por Gaston Pergola | gpergola@elpais.com.uy Ancel y Schneck no le pueden pedir mas a las apuestas publicitarias que realizaron con el "Loco" Sebastian Abreu y Sergio Gorzy. Por si sus premonitorios avisos hubiesen sido poco, el periodista como maestro de ceremonia y el futbolista como improvisado conductor se robaron la camara el martes pasado durante el homenaje a la seleccion de futbol en las afueras del Palacio Legisltativo. Ambas marcas, cada una a su manera, aposto con estrategias creativas a la seleccion uruguaya -a traves de estos dos personajes- y las propuestas terminaron siendo casi un presagio de lo que fue la realidad de Uruguay en la Copa del Mundo. Sergio Gorzy, el periodista deportivo devenido en fanatico insufrible del combinado celeste, que desde hace casi una decada viene pronosticando a Uruguay campeon del mundo, se convirtio tres meses antes de

In [63]:
str_text = auxiliar_full_lines
print('ANTES')
# cantidad de ocurrencias con texto -AUTOR-

pattern = r"Por \w* \w* \|"
results = re.findall(pattern, str_text, re.IGNORECASE)
print(len(results))

print('REEMPLAZO')

replace_pattern = r"(\w)(\s*Por \w* \w* \|)"
text = re.sub(replace_pattern, r'\1.', str_text, re.IGNORECASE)

replace_pattern = r"\s*Por \w* \w* \|"
text = re.sub(replace_pattern, '', str_text, 0, re.IGNORECASE)


print('DESPUES')
# cantidad de ocurrencias con texto -AUTOR-

pattern = r"Por \w* \w* \|"
results = re.findall(pattern, text, re.IGNORECASE)
print(len(results))


ANTES
598
REEMPLAZO
DESPUES
0


### String "AFP"


In [64]:
print(lines[93949])

x Lanzan proyecto de vehículos híbridos Berlín - El gobierno alemán, junto con Volkswagen y otros industriales, lanzó hoy en Berlín un ambicioso programa destinado a alentar el desarrollo de vehículos híbridos, es decir, con motores que combinan el carburante y la electricidad. El ministro alemán de Medio Ambiente, Sigmar Gabriel, prometió 15 millones de euros para apoyar este proyecto que pretende lanzar en cuatro años varios prototipos alimentados con electricidad procedente de fuentes renovables (viento, sol, agua). Otro de los objetivos fijados es el desarrollo de baterías de mayor capacidad. Además de Volkswagen, que aprovechó el jueves la ocasión para presentar su Golf TwinDrive, equipado de una nueva tecnología de motor híbrido, el programa cuenta con la participación del número uno de la energía alemán EON. El patrón del constructor, Martin Winterkorn, estimó imposible por el momento prescindir totalmente del carburante, pero aseguró que "el futuro perte

x Lanzan proyecto de vehículos híbridos Berlín - El gobierno alemán, junto con Volkswagen y otros industriales, lanzó hoy en Berlín un ambicioso programa destinado a alentar el desarrollo de vehículos híbridos, es decir, con motores que combinan el carburante y la electricidad. El ministro alemán de Medio Ambiente, Sigmar Gabriel, prometió 15 millones de euros para apoyar este proyecto que pretende lanzar en cuatro años varios prototipos alimentados con electricidad procedente de fuentes renovables (viento, sol, agua). Otro de los objetivos fijados es el desarrollo de baterías de mayor capacidad. Además de Volkswagen, que aprovechó el jueves la ocasión para presentar su Golf TwinDrive, equipado de una nueva tecnología de motor híbrido, el programa cuenta con la participación del número uno de la energía alemán EON. El patrón del constructor, Martin Winterkorn, estimó imposible por el momento prescindir totalmente del carburante, pero aseguró que "el futuro pertenece" al vehículo 100% eléctrico. Volkswagen, así como su competidor Daimler, presentarán en 2010 sus primeros modelos de funcionamiento completamente eléctrico. El investigador Ferdinand Dudenhoeffer, considerado en Alemania un oráculo de la industria automóvil, estimó en una entrevista publicada el jueves en el Neue Ruhr/Neue Rhein Zeitung que en 2025, "todos los autos vendidos en Europa serán eléctricos o híbridos". `AFP`


In [65]:
print(lines[124])

ARGENTINA Fiscal pide ocho años de cárcel para Menem Se lo acusa de contrabando de armas a Croacia y Ecuador durante su mandato.La sentencia estará en dos semanas.  Carlos Menem en el juzgado.  Foto: LA NACION | GDA Temas Contrabando de armas AFPvie may 31 2013 18:01 Un fiscal argentino pidió este viernes ocho años de prisión para el expresidente Carlos Menem por el contrabando de armas a Croacia y Ecuador durante su mandato, informó Infojus, portal que depende del ministerio de Justicia. El fiscal Marcelo Agüero Vera reclamó además el desafuero de Menem, actual senador, y su inhabilitación por 16 años para ejercer cargos públicos. Por otro lado, la fiscalía solicitó siete años de cárcel para el excanciller Oscar Camilión y ocho años para Diego Palleros, acusado como traficante de armas en la causa, según Infojus. Menem (82 años) y Camilión fueron encontrados culpables por "contrabando agravado de 6.500 toneladas de armamento y municiones a Croacia y Ecuador". El 

ARGENTINA Fiscal pide ocho años de cárcel para Menem Se lo acusa de contrabando de armas a Croacia y Ecuador durante su mandato.La sentencia estará en dos semanas.  Carlos Menem en el juzgado.  Foto: LA NACION | GDA Temas Contrabando de armas `AFP`vie may 31 2013 18:01 Un fiscal argentino pidió este viernes ocho años de prisión para el expresidente Carlos Menem por el contrabando de armas a Croacia y Ecuador durante su mandato, informó Infojus, portal que depende del ministerio de Justicia. El fiscal Marcelo Agüero Vera reclamó además el desafuero de Menem, actual senador, y su inhabilitación por 16 años para ejercer cargos públicos. Por otro lado, la fiscalía solicitó siete años de cárcel para el excanciller Oscar Camilión y ocho años para Diego Palleros, acusado como traficante de armas en la causa, según Infojus. Menem (82 años) y Camilión fueron encontrados culpables por "contrabando agravado de 6.500 toneladas de armamento y municiones a Croacia y Ecuador". El expresidente, quien estuvo presente en la audiencia, ocupa una banca por el gubernamental peronismo y por lo tanto tiene fueros que lo protegen de la cárcel, salvo que se promueva un juicio político. Los cañones, fusiles y otros pertrechos embarcados en Buenos Aires tenían como presunto destino Panamá y Venezuela, pero fueron desviados en una maniobra para eludir sendos embargos de armas que pesaban sobre Ecuador y Croacia, ambos envueltos en respectivas guerras en aquel entonces. El tribunal volverá a reunirse el viernes próximo y luego tendrá cinco días hábiles para fijar las penas. Menem y Camilión habían sido absueltos en 2011 por un tribunal oral, pero la Cámara de Casación revocó el fallo a comienzos de marzo. El delito de contrabando agravado contempla penas entre cuatro y 12 años de prisión. Vota por esta noticia:


#### Solucion


In [66]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto ¿Te interesa esta noticia?
pattern = r"AFP"
results = re.findall(pattern, str_text)
print(len(results))


11553


In [67]:
# REEMPLAZO:
testing_str = lines[93949]

replace_pattern = r"AFP"
result = re.sub(replace_pattern, '', testing_str)  
print(result)
print('')

x Lanzan proyecto de vehículos híbridos Berlín - El gobierno alemán, junto con Volkswagen y otros industriales, lanzó hoy en Berlín un ambicioso programa destinado a alentar el desarrollo de vehículos híbridos, es decir, con motores que combinan el carburante y la electricidad. El ministro alemán de Medio Ambiente, Sigmar Gabriel, prometió 15 millones de euros para apoyar este proyecto que pretende lanzar en cuatro años varios prototipos alimentados con electricidad procedente de fuentes renovables (viento, sol, agua). Otro de los objetivos fijados es el desarrollo de baterías de mayor capacidad. Además de Volkswagen, que aprovechó el jueves la ocasión para presentar su Golf TwinDrive, equipado de una nueva tecnología de motor híbrido, el programa cuenta con la participación del número uno de la energía alemán EON. El patrón del constructor, Martin Winterkorn, estimó imposible por el momento prescindir totalmente del carburante, pero aseguró que "el futuro perte

### Fechas

#### String de fecha de publicacion en formato "dia mes dd aaaa hh:mm"

In [68]:
print(lines[124])


ARGENTINA Fiscal pide ocho años de cárcel para Menem Se lo acusa de contrabando de armas a Croacia y Ecuador durante su mandato.La sentencia estará en dos semanas.  Carlos Menem en el juzgado.  Foto: LA NACION | GDA Temas Contrabando de armas AFPvie may 31 2013 18:01 Un fiscal argentino pidió este viernes ocho años de prisión para el expresidente Carlos Menem por el contrabando de armas a Croacia y Ecuador durante su mandato, informó Infojus, portal que depende del ministerio de Justicia. El fiscal Marcelo Agüero Vera reclamó además el desafuero de Menem, actual senador, y su inhabilitación por 16 años para ejercer cargos públicos. Por otro lado, la fiscalía solicitó siete años de cárcel para el excanciller Oscar Camilión y ocho años para Diego Palleros, acusado como traficante de armas en la causa, según Infojus. Menem (82 años) y Camilión fueron encontrados culpables por "contrabando agravado de 6.500 toneladas de armamento y municiones a Croacia y Ecuador". El 

ARGENTINA Fiscal pide ocho años de cárcel para Menem Se lo acusa de contrabando de armas a Croacia y Ecuador durante su mandato.La sentencia estará en dos semanas.  Carlos Menem en el juzgado.  Foto: LA NACION | GDA Temas Contrabando de armas AFP`vie may 31 2013 18:01` Un fiscal argentino pidió este viernes ocho años de prisión para el expresidente Carlos Menem por el contrabando de armas a Croacia y Ecuador durante su mandato, informó Infojus, portal que depende del ministerio de Justicia. El fiscal Marcelo Agüero Vera reclamó además el desafuero de Menem, actual senador, y su inhabilitación por 16 años para ejercer cargos públicos. Por otro lado, la fiscalía solicitó siete años de cárcel para el excanciller Oscar Camilión y ocho años para Diego Palleros, acusado como traficante de armas en la causa, según Infojus. Menem (82 años) y Camilión fueron encontrados culpables por "contrabando agravado de 6.500 toneladas de armamento y municiones a Croacia y Ecuador". El expresidente, quien estuvo presente en la audiencia, ocupa una banca por el gubernamental peronismo y por lo tanto tiene fueros que lo protegen de la cárcel, salvo que se promueva un juicio político. Los cañones, fusiles y otros pertrechos embarcados en Buenos Aires tenían como presunto destino Panamá y Venezuela, pero fueron desviados en una maniobra para eludir sendos embargos de armas que pesaban sobre Ecuador y Croacia, ambos envueltos en respectivas guerras en aquel entonces. El tribunal volverá a reunirse el viernes próximo y luego tendrá cinco días hábiles para fijar las penas. Menem y Camilión habían sido absueltos en 2011 por un tribunal oral, pero la Cámara de Casación revocó el fallo a comienzos de marzo. El delito de contrabando agravado contempla penas entre cuatro y 12 años de prisión. Vota por esta noticia:


In [69]:
print(lines[26])

SEGUIDILLA Otra tragedia en Rosario, cayó una "rueda gigante" y hay dos muertos Tras la explosión de principios de semana que mató a 13 personas y dejó varios desaparecidos, ahora hubo un accidente en un parque de diversiones. Foto: La Capital de Rosario. Temas Ascienden a 14 los muertos por la explosión de la ciudad de Rosario sáb ago 10 2013 19:35 Dos personas murieron y varias resultaron heridas en el parque de diversiones del Parque de la Independencia, en Rosario. Un carro de la famosa atracción "La vuelta al mundo" se desprendió desde la parte superior  y provocó la tragedia, según publican varios medios argentinos.  Según publica el diario La Capital de Rosario tres pequeños fueron derivados al Hospital de Niños Víctor Vilela, mientras el resto de los heridos, un total de diez, habrían sido trasladados al Hospital de Emergencias Clemente Alvarez. Según testigos que se encontraban el el parque de diversiones, el siniestro se produjo cuando "se desprendió un arné

SEGUIDILLA Otra tragedia en Rosario, cayó una "rueda gigante" y hay dos muertos Tras la explosión de principios de semana que mató a 13 personas y dejó varios desaparecidos, ahora hubo un accidente en un parque de diversiones. Foto: La Capital de Rosario. Temas Ascienden a 14 los muertos por la explosión de la ciudad de Rosario `sáb ago 10 2013 19:35` Dos personas murieron y varias resultaron heridas en el parque de diversiones del Parque de la Independencia, en Rosario. Un carro de la famosa atracción "La vuelta al mundo" se desprendió desde la parte superior  y provocó la tragedia, según publican varios medios argentinos.  Según publica el diario La Capital de Rosario tres pequeños fueron derivados al Hospital de Niños Víctor Vilela, mientras el resto de los heridos, un total de diez, habrían sido trasladados al Hospital de Emergencias Clemente Alvarez. Según testigos que se encontraban el el parque de diversiones, el siniestro se produjo cuando "se desprendió un arnés, el carro hizo columpio y se cayó. El muchacho que trabaja con la rueda hizo todo el esfuerzo, pero se descontroló totalmente", contó un testigo.  International Park está ubicado en pleno Parque de la Independencia, a sólo 15 cuadras del edificio que explotó el día martes. De hecho personal especializado en rescate, Bomberos y policías que estaban trabajando en la búsqueda de personas ausentes de la tragedia en Salta y Oroño llegaron al lugar para asistir a las víctimas. Vea el video que grabó una testigo en el momento del accidente y otro de los segundos posteriores: Vota por esta noticia:


#### Solucion


In [70]:
# str_text = sanitice_text(auxiliar_full_lines)
# cantidad de ocurrencias con fechas formato  dia mes nn YYYY hh:mm 
pattern = r"\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
results = re.findall(pattern, str_text)
print(len(results))
print(results[:5])


# Analizo el contexto de los casos encontrados
pattern = r"......\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d....."
results = re.findall(pattern, str_text)
print(len(results))
print(results[:10])

# Fechas al inicio del texto
pattern = r"^\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
results = re.findall(pattern, str_text, re.MULTILINE)
print(len(results))
print(results[:10])


11562
['mar jun 10 2014 18:42', 'sáb ago 10 2013 19:35', 'lun nov 11 2013 20:05', 'lun dic 23 2013 10:09', 'lun may 27 2013 09:32']
11236
['rísAFPmar jun 10 2014 18:42 En u', 'sario sáb ago 10 2013 19:35 Dos ', 'cedes lun nov 11 2013 20:05 Ocho', ' a AFPlun dic 23 2013 10:09 Las ', 'borto lun may 27 2013 09:32 En d', 'ernes mar jun 17 2014 17:41 En e', 'Temas mié may 14 2014 11:06 Si n', ' hoy? jue jun 12 2014 21:26 La a', 'París vie dic 20 2013 03:00 La m', ' Rojaslun sep 16 2013 09:56 El h']
260
['sáb ago 17 2013 17:36', 'lun ago 11 2014 04:00', 'lun jun 16 2014 04:00', 'mié abr 23 2014 04:00', 'mié may 14 2014 04:00', 'mié jun 25 2014 16:44', 'lun ene 20 2014 03:01', 'sáb mar 29 2014 04:00', 'sáb abr 26 2014 04:05', 'dom jun 29 2014 04:00']


In [71]:
lines[88926]

'ANA INÉS MARTÍNEZ (Periodista y presentadora en Subrayado) Así lo vio Los temas que estuvieron en la vuelta analizados por una figura invitada. Temas Así lo vio Aguada campeón luego de 36 años. Hay dos lecturas para hacer. Por un lado lo deportivo. Por momentos, Aguada dependió de Leandro García Morales, pero tuvo juego en equipo y mucha garra, y por eso ganó varios partidos en el cierre. A veces se dice que los árbitros miden a García Morales, la figura del basquet nacional, con otra vara. Eso es cuestionable, pero me pareció un justo campeón. El otro tema es la hinchada. Ahora está de moda la frase "ah, ahora todos son hinchas de aguada". Yo estuve en la cancha con mi hijo, y realmente me impresionó la pasión de los hinchas, vi gente llorar en serio, con ruido. Cuando me iba, le pedí al taxi que pasara junto a los hinchas que caminaban del Palacio Peñarol a la sede del club, e hicieron una parada en el Palacio Legislativo para sacar fotos y tirar fuegos. Nunca vi u

#### Fecha con formato -dia mmm dd `YYYY- (sin hora)

In [72]:
# Hay casos donde no tienen la hora

# str_text = auxiliar_full_lines
# cantidad de ocurrencias con formato  dia mes nn YYYY --- SIN HORA
pattern = r"\w\w\w \w\w\w \d\d \d\d\d\d [^\d\d:\d\d]"
results = re.findall(pattern, str_text)
print(len(results))
print(results[:5])

# Analizo el contexto de los casos encontrados
pattern = r"..........\w\w\w \w\w\w \d\d \d\d\d\d [^.\d\d:\d\d]....."
results = re.findall(pattern, str_text)
print(len(results))
print(results[:15])

2650
['jue jul 17 2014 E', 'lun may 12 2014 E', 'jue jul 10 2014 E', 'lun jul 28 2014 N', 'mar jun 24 2014 E']
2538
[' Agustini jue jul 17 2014 El pro', 'ris Brown lun may 12 2014 El jue', 'it fiscal jue jul 10 2014 Este e', 'RATT VIÑESlun jul 28 2014 Nacida', 'NACIÓN/GDAmar jun 24 2014 El est', 'EGO CASTROmié jun 25 2014 El pit', 'A RUGGIEROdom jul 13 2014 Belén ', 'a y Rusia mar jun 24 2014 Una gu', 'RLOS TAPIAvie jul 11 2014 El MSP', 'curio/ GDAdom jun 15 2014 Mientr', 'ANSA Y EFEmar ago 12 2014 Sin em', 'L CAIROAFPmar jun 24 2014 A nive', 'án Cabrerasáb may 24 2014 Todo e', 'EVANSA/AFPsáb jun 21 2014 Según ', 'ANDO MEXÍAlun ago 11 2014 True D']


#### Fecha formato dd mmm YYYY

In [73]:
print(lines[107373])

23 ene 2014 La carrera, que va por la 69a edición, se disputará el sábado 8 de febrero. La prueba clásica del balneario de los cerros, se disputará en un circuito que abarca ocho kilómetros y parte de Rambla de los Argentinos y Simón del Pino, continúa por la rambla hasta la calle Maipú, sigue por Uruguay, sube al San Antonio y retorna al lugar en que se efectuó la largada. Las inscripciones se realizarán los días 6, 7 y 8 de febrero, entre las 9:00 y las 20:00 horas, en el Campus Municipal (Hall Estadio); en Cedemcar (San Carlos); en la Pista de Atletismo de Montevideo y en la Casa de la Cultura de Piriápolis. El costo de la inscripción es de $ 250 y se puede abonar previamente en locales de Red Pagos de todo el país. Los menores de 18 años necesitan la firma de un adulto responsable en el formulario de inscripción; los participantes con discapacidades y los menores de 14 años podrán participar en forma gratuita. Los niños partirán a las 20:30 horas y competirán 

`23 ene 2014` La carrera, que va por la 69a edición, se disputará el sábado 8 de febrero. La prueba clásica del balneario de los cerros, se disputará en un circuito que abarca ocho kilómetros y parte de Rambla de los Argentinos y Simón del Pino, continúa por la rambla hasta la calle Maipú, sigue por Uruguay, sube al San Antonio y retorna al lugar en que se efectuó la largada. Las inscripciones se realizarán los días 6, 7 y 8 de febrero, entre las 9:00 y las 20:00 horas, en el Campus Municipal (Hall Estadio); en Cedemcar (San Carlos); en la Pista de Atletismo de Montevideo y en la Casa de la Cultura de Piriápolis. El costo de la inscripción es de $ 250 y se puede abonar previamente en locales de Red Pagos de todo el país. Los menores de 18 años necesitan la firma de un adulto responsable en el formulario de inscripción; los participantes con discapacidades y los menores de 14 años podrán participar en forma gratuita. Los niños partirán a las 20:30 horas y competirán en tres categorías: menores de 7 años (750 metros), menores de 12 años (mil metros) y menores de 15 años (dos mil metros); los adultos largarán a las 21:30 horas. La inscripción incluye el número de corredor, el chip de control de tiempo, la hidratación y medalla al final de la prueba. Entre 3.000 atletas, en 2013, el piriapolense Santiago Casco obtuvo el primer puesto, haciendo historia, no sólo por ser primer lugareño que ganó la carrera, sino también la San Felipe y Santiago en Montevideo y la San Fernando en Maldonado. El atleta de Pueblo Obrero también se había despachado con un triunfo en el Interplayas de Las Cañas, en Fray Bentos. Vota por esta noticia:


In [74]:
#  str_text = sanitice_text(auxiliar_full_lines)
# cantidad de ocurrencias con fechas formato  nn mes YYYY 
pattern = r"\d\d \w\w\w \d\d\d\d"
results = re.findall(pattern, str_text)
print(len(results))

print(results[:50])

pattern = r"....\d\d \w\w\w \d\d\d\d......."
results = re.findall(pattern, str_text)
print(len(results))
print(results[:50])

pattern = r"^\d\d \w\w\w \d\d\d\d"
results = re.findall(pattern, str_text, re.MULTILINE)
print(len(results))
print(results[:50])


6114
['06 feb 2014', '04 abr 2014', '08 may 2014', '09 may 2014', '03 may 2014', '06 abr 2014', '26 abr 2014', '24 abr 2014', '24 ene 2014', '16 mar 2014', '20 mar 2014', '23 abr 2014', '17 feb 2014', '01 feb 2014', '27 abr 2014', '01 feb 2014', '26 feb 2014', '10 mar 2014', '07 ago 2014', '30 abr 2014', '14 abr 2014', '04 jul 2014', '21 feb 2014', '17 mar 2014', '01 800 5520', '15 jun 2014', '04 feb 2014', '09 abr 2014', '19 feb 2014', '29 abr 2014', '08 may 2014', '21 mar 2014', '13 abr 2014', '12 abr 2014', '20 mar 2014', '14 mar 2014', '15 jun 2014', '10 feb 2014', '21 feb 2014', '04 jul 2014', '20 feb 2014', '01 feb 2014', '28 mar 2014', '26 feb 2014', '17 mar 2014', '05 may 2014', '09 abr 2014', '07 feb 2014', '06 abr 2014', '29 abr 2014']
5931
['STOK06 feb 2014 La ent', 'mas 04 abr 2014 POR AN', 'ELIN08 may 2014 A medi', 'ARDO09 may 2014 Jorge ', 'sta 03 may 2014 Brenta', ' EFE06 abr 2014 El est', 'das 26 abr 2014 Consen', ' EFE24 abr 2014 En un ', 'ARCO20 mar 2014 El 8 d', 'rto

#### Conclusiones sobre fechas

In [75]:
# CONCLUSIONES SOBRE LAS FECHAS:
#  - Se detectaron 3 formatos: < dia mes dd aaaa hh:mm >, <dia mes dd aaaa>, <dd mmm aaaa>
#  - A veces las fechas estan al inicio
#  - A continuacion de las fechas, siempre hay un inicio de Oracion --> tendria que haber un punto a continuacion

# Formato dd mmm YYYY
# al inicio
print('ANTES')
testing_str = lines[107373]
print(testing_str)
replace_pattern = r"^\d\d \w\w\w \d\d\d\d"
result = re.sub(replace_pattern, '', testing_str)  
print('DESPUES')
print(result)
print('----------------------------------------------------------------')

# dentro el string
print('ANTES')
testing_str = lines[39]
print(testing_str)
replace_pattern = r"\d\d \w\w\w \d\d\d\d"
result = re.sub(replace_pattern, '.', testing_str)  
print('DESPUES')
print(result)
print('----------------------------------------------------------------')

# Formato  dia mes nn YYYY hh:mm 
# al inicio
print('ANTES')
testing_str = lines[15719]
print(testing_str)
replace_pattern = r"^\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
result = re.sub(replace_pattern, '', testing_str)
print('DESPUES')
print(result)
print('----------------------------------------------------------------')

# dentro del string
print('ANTES')
testing_str = lines[51]
print(testing_str)
replace_pattern = r"\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
result = re.sub(replace_pattern, '.', testing_str)
print('DESPUES')
print(result)
print('----------------------------------------------------------------')


# Formato -dia mmm dd YYYY- (sin hora)
# al inicio
print('ANTES')
testing_str = lines[6267]
print(testing_str)
replace_pattern = r"^\w\w\w \w\w\w \d\d \d\d\d\d"
result = re.sub(replace_pattern, '', testing_str)
print('DESPUES')
print(result)
print('----------------------------------------------------------------')


# dentro del string
print('ANTES')
testing_str = lines[229]
print(testing_str)
replace_pattern = r"\w\w\w \w\w\w \d\d \d\d\d\d"
result = re.sub(replace_pattern, '.', testing_str)
print('DESPUES')
print(result)
print('----------------------------------------------------------------')

ANTES
23 ene 2014 La carrera, que va por la 69a edición, se disputará el sábado 8 de febrero. La prueba clásica del balneario de los cerros, se disputará en un circuito que abarca ocho kilómetros y parte de Rambla de los Argentinos y Simón del Pino, continúa por la rambla hasta la calle Maipú, sigue por Uruguay, sube al San Antonio y retorna al lugar en que se efectuó la largada. Las inscripciones se realizarán los días 6, 7 y 8 de febrero, entre las 9:00 y las 20:00 horas, en el Campus Municipal (Hall Estadio); en Cedemcar (San Carlos); en la Pista de Atletismo de Montevideo y en la Casa de la Cultura de Piriápolis. El costo de la inscripción es de $ 250 y se puede abonar previamente en locales de Red Pagos de todo el país. Los menores de 18 años necesitan la firma de un adulto responsable en el formulario de inscripción; los participantes con discapacidades y los menores de 14 años podrán participar en forma gratuita. Los niños partirán a las 20:30 horas y compet

In [76]:
# str_text = sanitice_text(auxiliar_full_lines)
print('==== ANTES ====')
print('nn mes YYYY')
pattern = r"^\d\d \w\w\w \d\d\d\d"
results = re.findall(pattern, str_text, re.MULTILINE)
print(f'inicio - {len(results)}')

pattern = r".\d\d \w\w\w \d\d\d\d"
results = re.findall(pattern, str_text)
print(f'medio - {len(results)}')


print('dia mes dd aaaa hh:mm')
pattern = r"^\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
results = re.findall(pattern, str_text, re.MULTILINE)
print(f'inicio - {len(results)}')

pattern = r".\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
results = re.findall(pattern, str_text)
print(f'medio - {len(results)}')


print('dia mes dd aaaa')
pattern = r"^\w\w\w \w\w\w \d\d \d\d\d\d [^\d\d:\d\d]"
results = re.findall(pattern, str_text, re.MULTILINE)
print(f'inicio - {len(results)}')

pattern = r".\w\w\w \w\w\w \d\d \d\d\d\d [^\d\d:\d\d]"
results = re.findall(pattern, str_text)
print(f'medio - {len(results)}')
print('=========')
print('==== REEMPLAZO ====')

# pipeline de reemplazo
text = str_text
# Formato dd mmm YYYY
# al inicio
replace_pattern = r"^\d\d \w\w\w \d\d\d\d"
text = re.sub(replace_pattern, '', text, re.MULTILINE)  

# dentro el string
replace_pattern = r"\d\d \w\w\w \d\d\d\d"
text = re.sub(replace_pattern, '.', text)  

# Formato  dia mes nn YYYY hh:mm 
# al inicio
replace_pattern = r"^\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
text = re.sub(replace_pattern, '', text, re.MULTILINE)

# dentro del string
replace_pattern = r"\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
text = re.sub(replace_pattern, '.', text)

# Formato -dia mmm dd YYYY- (sin hora)
# al inicio
replace_pattern = r"^\w\w\w \w\w\w \d\d \d\d\d\d"
text = re.sub(replace_pattern, '', text, re.MULTILINE)

# dentro del string
replace_pattern = r"\w\w\w \w\w\w \d\d \d\d\d\d"
text = re.sub(replace_pattern, '.', text)

print('=========')
print('==== DESPUES ====')
print('nn mes YYYY')
pattern = r"^\d\d \w\w\w \d\d\d\d"
results = re.findall(pattern, text, re.MULTILINE)
print(f'inicio - {len(results)}')

pattern = r".\d\d \w\w\w \d\d\d\d"
results = re.findall(pattern, text)
print(f'medio - {len(results)}')


print('dia mes dd aaaa hh:mm')
pattern = r"^\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
results = re.findall(pattern, text, re.MULTILINE)
print(f'inicio - {len(results)}')

pattern = r".\w\w\w \w\w\w \d\d \d\d\d\d \d\d:\d\d"
results = re.findall(pattern, text)
print(f'medio - {len(results)}')


print('dia mes dd aaaa')
pattern = r"^\w\w\w \w\w\w \d\d \d\d\d\d [^\d\d:\d\d]"
results = re.findall(pattern, text, re.MULTILINE)
print(f'inicio - {len(results)}')

pattern = r".\w\w\w \w\w\w \d\d \d\d\d\d [^\d\d:\d\d]"
results = re.findall(pattern, text)
print(f'medio - {len(results)}')

==== ANTES ====
nn mes YYYY
inicio - 180
medio - 5934
dia mes dd aaaa hh:mm
inicio - 260
medio - 11302
dia mes dd aaaa
inicio - 48
medio - 2602
==== REEMPLAZO ====
==== DESPUES ====
nn mes YYYY
inicio - 0
medio - 0
dia mes dd aaaa hh:mm
inicio - 0
medio - 0
dia mes dd aaaa
inicio - 0
medio - 0


### String "Foto: -origen-"

In [77]:
print(lines[124])

ARGENTINA Fiscal pide ocho años de cárcel para Menem Se lo acusa de contrabando de armas a Croacia y Ecuador durante su mandato.La sentencia estará en dos semanas.  Carlos Menem en el juzgado.  Foto: LA NACION | GDA Temas Contrabando de armas AFPvie may 31 2013 18:01 Un fiscal argentino pidió este viernes ocho años de prisión para el expresidente Carlos Menem por el contrabando de armas a Croacia y Ecuador durante su mandato, informó Infojus, portal que depende del ministerio de Justicia. El fiscal Marcelo Agüero Vera reclamó además el desafuero de Menem, actual senador, y su inhabilitación por 16 años para ejercer cargos públicos. Por otro lado, la fiscalía solicitó siete años de cárcel para el excanciller Oscar Camilión y ocho años para Diego Palleros, acusado como traficante de armas en la causa, según Infojus. Menem (82 años) y Camilión fueron encontrados culpables por "contrabando agravado de 6.500 toneladas de armamento y municiones a Croacia y Ecuador". El 

ARGENTINA Fiscal pide ocho años de cárcel para Menem Se lo acusa de contrabando de armas a Croacia y Ecuador durante su mandato.La sentencia estará en dos semanas.  Carlos Menem en el juzgado.  `Foto: LA NACION` | GDA Temas Contrabando de armas AFPvie may 31 2013 18:01 Un fiscal argentino pidió este viernes ocho años de prisión para el expresidente Carlos Menem por el contrabando de armas a Croacia y Ecuador durante su mandato, informó Infojus, portal que depende del ministerio de Justicia. El fiscal Marcelo Agüero Vera reclamó además el desafuero de Menem, actual senador, y su inhabilitación por 16 años para ejercer cargos públicos. Por otro lado, la fiscalía solicitó siete años de cárcel para el excanciller Oscar Camilión y ocho años para Diego Palleros, acusado como traficante de armas en la causa, según Infojus. Menem (82 años) y Camilión fueron encontrados culpables por "contrabando agravado de 6.500 toneladas de armamento y municiones a Croacia y Ecuador". El expresidente, quien estuvo presente en la audiencia, ocupa una banca por el gubernamental peronismo y por lo tanto tiene fueros que lo protegen de la cárcel, salvo que se promueva un juicio político. Los cañones, fusiles y otros pertrechos embarcados en Buenos Aires tenían como presunto destino Panamá y Venezuela, pero fueron desviados en una maniobra para eludir sendos embargos de armas que pesaban sobre Ecuador y Croacia, ambos envueltos en respectivas guerras en aquel entonces. El tribunal volverá a reunirse el viernes próximo y luego tendrá cinco días hábiles para fijar las penas. Menem y Camilión habían sido absueltos en 2011 por un tribunal oral, pero la Cámara de Casación revocó el fallo a comienzos de marzo. El delito de contrabando agravado contempla penas entre cuatro y 12 años de prisión. Vota por esta noticia:


In [78]:
print(lines[26])

SEGUIDILLA Otra tragedia en Rosario, cayó una "rueda gigante" y hay dos muertos Tras la explosión de principios de semana que mató a 13 personas y dejó varios desaparecidos, ahora hubo un accidente en un parque de diversiones. Foto: La Capital de Rosario. Temas Ascienden a 14 los muertos por la explosión de la ciudad de Rosario sáb ago 10 2013 19:35 Dos personas murieron y varias resultaron heridas en el parque de diversiones del Parque de la Independencia, en Rosario. Un carro de la famosa atracción "La vuelta al mundo" se desprendió desde la parte superior  y provocó la tragedia, según publican varios medios argentinos.  Según publica el diario La Capital de Rosario tres pequeños fueron derivados al Hospital de Niños Víctor Vilela, mientras el resto de los heridos, un total de diez, habrían sido trasladados al Hospital de Emergencias Clemente Alvarez. Según testigos que se encontraban el el parque de diversiones, el siniestro se produjo cuando "se desprendió un arné

SEGUIDILLA Otra tragedia en Rosario, cayó una "rueda gigante" y hay dos muertos Tras la explosión de principios de semana que mató a 13 personas y dejó varios desaparecidos, ahora hubo un accidente en un parque de diversiones. `Foto: La Capital de Rosario`. Temas Ascienden a 14 los muertos por la explosión de la ciudad de Rosario sáb ago 10 2013 19:35 Dos personas murieron y varias resultaron heridas en el parque de diversiones del Parque de la Independencia, en Rosario. Un carro de la famosa atracción "La vuelta al mundo" se desprendió desde la parte superior  y provocó la tragedia, según publican varios medios argentinos.  Según publica el diario La Capital de Rosario tres pequeños fueron derivados al Hospital de Niños Víctor Vilela, mientras el resto de los heridos, un total de diez, habrían sido trasladados al Hospital de Emergencias Clemente Alvarez. Según testigos que se encontraban el el parque de diversiones, el siniestro se produjo cuando "se desprendió un arnés, el carro hizo columpio y se cayó. El muchacho que trabaja con la rueda hizo todo el esfuerzo, pero se descontroló totalmente", contó un testigo.  International Park está ubicado en pleno Parque de la Independencia, a sólo 15 cuadras del edificio que explotó el día martes. De hecho personal especializado en rescate, Bomberos y policías que estaban trabajando en la búsqueda de personas ausentes de la tragedia en Salta y Oroño llegaron al lugar para asistir a las víctimas. Vea el video que grabó una testigo en el momento del accidente y otro de los segundos posteriores: Vota por esta noticia:


In [79]:
lines[1215]

'Semana de la Moda La española Desigual se presentó en New York Con el desembarco de la marca española Desigual y un primer desfile consagrado a las mujeres "rellenitas", la Fashion Week arrancó este jueves en Nueva York. Las gemelas Olsen. Foto: AP Heidi Klumm en el desfile de BCBG de Max Azria. Foto: AP La protagonista de Sex and the City, Sarah Jessica Parker dijo presente. Foto: AP La marca española Desigual presentó sus diseños. Foto: EFE La marca española Desigual presentó sus diseños. Foto: EFE La marca española Desigual presentó sus diseños. Foto: EFE La marca española Desigual presentó sus diseños. Foto: EFE Foto: AP Max y Luvob Azria luego de su desfile. Foto: AP Foto: AP Desigual AFPvie sep 6 2013 09:28 Con modelos simulando a veces pasos de un baile de rock y que enviaban besos al público, Desigual dio este jueves sus primeros pasos llenos de energía en la cita obligada de la moda neoyorquina. La atmósfera era decididamente Desigual, con colores estampado

#### Solucion


In [80]:
# Ocurrencias de texto "Foto:"
pattern = r"Foto:"
results = re.findall(pattern, auxiliar_full_lines)
print(f'Ocurrencias de texto "Foto:" - {len(results)}')

pattern = r"..........Foto:...................."
results = re.findall(pattern, auxiliar_full_lines)
print(f'CONTEXTO de texto "Foto:" - {len(results)}')
print(results[:20])

# hay separadores como . | /
pattern = "Foto:.*?\."
results = re.findall(pattern, auxiliar_full_lines)
print(f'Ocurrencias de texto "Foto:" - {len(results)}')

# comentario: hay casos como "Foto: AP .... " que incluyen la descripcion de la foto
# Semana de la Moda La española Desigual se presentó en New York Con el desembarco de la marca española Desigual 
# y un primer desfile consagrado a las mujeres "rellenitas", la Fashion Week arrancó este jueves en Nueva York. Las gemelas Olsen.
# Foto: AP Heidi Klumm en el desfile de BCBG de Max Azria. Foto: AP La protagonista de Sex and the City, Sarah Jessica Parker dijo 
# presente. Foto: AP La marca española Desigual presentó sus diseños. Foto: EFE La marca española Desigual presentó sus diseños.
# Foto: EFE La marca española Desigual presentó sus diseños. Foto: EFE La marca española Desigual presentó sus diseños. Foto: EFE
# Foto: AP Max y Luvob Azria luego de su desfile. Foto: AP Foto: AP Desigual AFPvie sep 6 2013 09:28 Con modelos simulando a veces p

# Lo mimso con "Foto: EFE", creo que de momento voy a eliminar solo el string siguiente een esos casos, estan complejos

pattern = r"(Foto:.*?)(\/|\.|AP|EFE|AFP|Archivo El Pais|Temas|Facebook Comite de los Derechos del Nino del Uruguay Centros del Sirpa|Alexis Ferreira|Gentileza Policia de San Jose|Maria Ines Hiriart|Ricardo Figueredo|Facebook Carolina Mallo Sosa|Facebook Jose Maria Techera|Facebook Roberto Caseres|Facebook Richard Silveira|Dilva Devita|Facebook Comite de los Derechos del Nino|El Pais Entierro del policia Ariel Silva|Ariel Colmegna Primera boda  bajo la ley) "
results = re.findall(pattern, auxiliar_full_lines)
print(f'Ocurrencias de texto "Foto: PATTERN" - {len(results)}')
print(results[:20])

replace_pattern = pattern
cleaned = re.sub(replace_pattern, '.', auxiliar_full_lines)

print('limpiado! \n \n')
pattern = r"Foto:........................................."
results = re.findall(pattern, cleaned)
print(f'Ocurrencias de texto prelimpiado "Foto: PATTERN" - {len(results)}')
print(results[:20])


Ocurrencias de texto "Foto:" - 10096
CONTEXTO de texto "Foto:" - 9565
[' Almagro. Foto: Francisco Flores / ', 'ersiones. Foto: La Capital de Rosar', 'S digital Foto: El País. Fotógrafo:', 'Mercedes. Foto: Daniel Rojas. Temas', ' medidas. Foto: AP Temas exportacio', 'Aliójina. Foto: AFP Temas La música', 'r García. Foto: Archivo El País Tem', 'a Brasil".Foto: Archivo El País. Te', ' Perrone. Foto: Daniel Ayala Temas ', 'sociales. Foto: Julio Barcelos Tema', 'juzgado.  Foto: LA NACION | GDA Tem', 'enedores. Foto: Archivo Temas Parag', 'gravedad. Foto: Gentileza de José L', 'ue Viana. Foto: Archivo de El País.', 'diactiva. Foto: AFP Temas robaron m', 'y Chávez. Foto: Archivo El País Tem', 'de clase. Foto: Archivo El País Tem', 'ya Mansa. Foto: Marcelo Bonjour Tem', 'daptarse. Foto:archivo El País Tema', 'pietario. Foto: Agencias Temas Trib']
Ocurrencias de texto "Foto:" - 9740
Ocurrencias de texto "Foto: PATTERN" - 9557
[('Foto: Francisco Flores ', '/'), ('Foto: La Capital de Rosario', '.

In [81]:
for text in results:
  print(text)

Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: Facebook Comité de los Derechos del Niño
Foto: El País Entierro del policía Ariel Silva
Foto: Gentileza Policía de San José No salgas 
Foto: María I



---



### String "Otras Ediciones" (probablemente al final del texto)


In [82]:
print(lines[44335])

Los sucesores de Nelson Mandela no consiguen inspirar una integración más armoniosa El legado del "apartheid" Un video grabado en una universidad sudafricana recuerda los días de racismo institucionalizado en ese país, y le atesta un nuevo golpe al sueño de la Nación Arcoiris. THE ECONOMIST LA RAZA VOLVIÓ A OCUPAR los titulares de la prensa y las ondas de radio y televisión sudafricana. Un video filmado por cuatro estudiantes universitarios blancos retrata un humillante rito de iniciación para cuatro limpiadoras negras a la residencia estudiantil. En la filmación se las ve de rodillas, comiendo de un plato en el cual los estudiantes, aparentemente, habían orinado. El video, claramente destinado a socavar la integración racial en las residencias estudiantiles del país, generó un shock que se propagó en una onda expansiva en la sociedad sudafricana y más allá. El video se conoció poco tiempo después de otros desagradables incidentes raciales. En enero, un adolescente b

Los sucesores de Nelson Mandela no consiguen inspirar una integración más armoniosa El legado del "apartheid" Un video grabado en una universidad sudafricana recuerda los días de racismo institucionalizado en ese país, y le atesta un nuevo golpe al sueño de la Nación Arcoiris. THE ECONOMIST LA RAZA VOLVIÓ A OCUPAR los titulares de la prensa y las ondas de radio y televisión sudafricana. Un video filmado por cuatro estudiantes universitarios blancos retrata un humillante rito de iniciación para cuatro limpiadoras negras a la residencia estudiantil. En la filmación se las ve de rodillas, comiendo de un plato en el cual los estudiantes, aparentemente, habían orinado. El video, claramente destinado a socavar la integración racial en las residencias estudiantiles del país, generó un shock que se propagó en una onda expansiva en la sociedad sudafricana y más allá. El video se conoció poco tiempo después de otros desagradables incidentes raciales. En enero, un adolescente blanco y armado, mató a cuatro personas, incluida una madre y su bebé, en una zona rural. Aparentemente, sus móviles eran racistas. El mes pasado, Irvin Khoza, el líder negro encargado de organizar el próximo campeonato mundial de fútbol, a realizarse en Sudáfrica dentro de dos años, generó reacciones iracundas cuando le dijo a un periodista que dejara de pensar como un "kaffir", término ofensivo para un sudafricano negro. Y el Foro de Periodistas Negros se metió en un brete cuando le prohibió a colegas blancos asistir a una reunión con Jacob Zuma, el nuevo presidente del Congreso Nacional Africano, el partido en el poder. Catorce años después del fin del "apartheid", la pregunta es: ¿se está desvaneciendo el ideal de la Nación Arcoiris ? Para nada. Sudáfrica ha recorrido un largo camino desde los días del racismo institucionalizado. La transición a la democracia ha sido extraordinariamente fluida, considerando el amargo pasado del país. No es corriente que se informe sobre violencia motivada por cuestiones raciales. La vasta mayoría de los sudafricanos quieren una democracia no-racial que respete las diferencias. Y hay leyes que castigan la discriminación injusta, además de una política de "fortalecimiento económico negro", destinada a corregir pasadas injusticias. Aunque los negros siguen estando representados excesivamente en las estadísticas sobre pobres y desempleados, una emergente clase media negra está lentamente disolviendo las fronteras raciales y sociales. Escuelas y universidades que antes tenían una política de segregación, hoy incluyen estudiantes de todos los colores. Hasta la University of the Free State, donde se filmó el video racista y donde las clases se impartían en afrikaans (la lengua de los colonos holandeses), tiene una mayoría de estudiantes negros. Y una mayoría de sudafricanos opina que las relaciones raciales están mejorando. Integración a la fuerza Aún así, Sudáfrica está lejos de ser una nación daltónica. Personas de distintas razas se sientan en los mismos restaurantes. Pero en diferentes mesas. La coexistencia pacífica, algo de lo que el país disfruta, no es lo mismo que integración. La población de las zonas rurales, además, es menos propensa a la mezcla que la gente de las grandes ciudades como Johannesburg. De acuerdo a David Maimela, del Congreso Estudiantil de Sudáfrica, la integración de las razas en las universidades es de la boca para afuera. El Frente de la Libertad Plus, un pequeño partido en la oposición que representa mayoritariamente a los afrikaners, se opone a lo que llama la "integración a la fuerza" de las residencias estudiantiles. El partido sostiene que aquellos afrikaners que temen por su identidad cultural y por su idioma, corren el riesgo de no ser tenidos en cuenta. Pero Tim Du Plessis, editor del Rapport, un semanario afrikaans, dice que preocupaciones legítimas, como la del idioma, han sido usadas como pretexto para resistirse a la integración racial. Muchos sudafricanos blancos -tanto los que hablan inglés como los que se expresan en afrikaans- se sienten cada vez más frustrados por la discriminación positiva. Mientras que Nelson Mandela inspiraba a muchos de ellos con su visión acerca del país y su futuro, sus sucesores, incluido el presidente Thabo Mbeki, no han logrado lo mismo. Muchos blancos piensan que el Congreso Nacional Africano está perdiendo su estatura moral y derivando en una fuerza política más insular y emigran. Al mismo tiempo, muchos de sus compatriotas negros se sienten frustrados por la lentitud en el ritmo de los cambios. Aún así, la mayoría de los sudafricanos, sin distinción, rechazan el racismo crudo. El video ha indignado a casi todos, y ha sido condenado de forma unánime. La medida del éxito de Sudáfrica en este tema no es la erradicación del racismo -ningún país multiracial ha logrado eso- sino cómo maneja ese urticante problema. Las protestas contra el video han sido, hasta ahora, pacíficas. Los cuatro estudiantes responsables pueden enfrentar demandas judiciales. El señor Khoza fue censurado. Y la comisión de Derechos Humanos sudafricana investiga las quejas contra el Foro de los Periodistas Negros. Tseliso Thipanyane, director de la comisión, dice que "deberíamos involucrarnos activamente en estos temas, en vez de desear que desaparezcan por arte de magia". La intolerancia grupal no es un tema que pueda tratarse de manera maniquea y reducirla a una cuestión de blanco o negro. Una reciente investigación llevada a cabo por una encuestadora local comprobó que el 42 % de los habitantes de los barrios más pobres -aquellos que sienten más cercana la competencia por trabajo y servicios- se consideran amenazados por "otras culturas". Esa cifra es alarmantemente más alta que el promedio nacional, que se ubica en un 29 %. Ataques de sudafricanos negros a comerciantes somalíes e inmigrantes de Zimbabwe parecen cada vez más comunes. Y la escasez de vivienda en el Cabo Occidental alimenta la tensión entre sudafricanos "de color" (mestizos) y negros. En un país tan diverso como Sudáfrica, esto es algo que está dentro de lo previsible. El video, en tanto, obligó a todos a esforzarse más para idear distintas maneras de promover una mayor armonía. `Otras Ediciones`


In [83]:
print(lines[61726])

IRIS DEL PÚBLICO Los Iris del público en la web Desde el sábado pasado, está disponible en El País Digital el formulario que permite a los lectores elegir a los ganadores de los Premios Iris del Público, que se otorgan por segundo año consecutivo. Los mismos se votan vía Internet y premian a el Mejor Programa de Televisión Nacional, Mejor Banda de Rock Nacional y Mejor Obra de Teatro. Los votos se acumulan durante dos semanas (quedan sólo ocho días para seguir participando) y los ganadores se darán a conocer en la ceremonia de entrega de los Iris, el próximo 20 de mayo en el Salón Flamingo. Los ganadores del año pasado fueron Víctimas y victimarios (Televisión), No Te Va Gustar (Rock) y El método Gronholm (Teatro). Otras Ediciones



IRIS DEL PÚBLICO Los Iris del público en la web Desde el sábado pasado, está disponible en El País Digital el formulario que permite a los lectores elegir a los ganadores de los Premios Iris del Público, que se otorgan por segundo año consecutivo. Los mismos se votan vía Internet y premian a el Mejor Programa de Televisión Nacional, Mejor Banda de Rock Nacional y Mejor Obra de Teatro. Los votos se acumulan durante dos semanas (quedan sólo ocho días para seguir participando) y los ganadores se darán a conocer en la ceremonia de entrega de los Iris, el próximo 20 de mayo en el Salón Flamingo. Los ganadores del año pasado fueron Víctimas y victimarios (Televisión), No Te Va Gustar (Rock) y El método Gronholm (Teatro). `Otras Ediciones`


#### Solucion

In [84]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto -Otras ediciones-
pattern = r"Otras Ediciones"
results = re.findall(pattern, str_text)
print(len(results))

# cantidad de ocurrencias con texto  -Otras ediciones- y salto de linea
pattern_1 = r"Otras Ediciones\n"
results_1 = re.findall(pattern_1, str_text)
print(len(results_1))

# cantidad de ocurrencias con texto -Otras ediciones-
pattern = r"Otras Ediciones"
results = re.findall(pattern, str_text, re.IGNORECASE)
print(len(results))

# CONCLUSION
# siempre estan al final del texto.
# existen casos en minusculas QUE NO DEBO BORRAR.

3418
3418
3445


In [85]:
print("ANTES:")
pattern = r"Otras Ediciones\n"
results = re.findall(pattern, str_text)
print(f'cantidad de ocurrencias: {len(results)}')

# analisis de recorrer todo el texto
replace_pattern = r"Otras Ediciones\n"
total_result = re.sub(replace_pattern, '', str_text)  

print("DESPUES:")
pattern = r"Otras Ediciones\n"
results = re.findall(pattern, total_result)
print(f'cantidad de ocurrencias: {len(results)}')


ANTES:
cantidad de ocurrencias: 3418
DESPUES:
cantidad de ocurrencias: 0


### String del formato "| -Lugar- @ |"



In [86]:
print(lines[80883])

Trampear la voluntad popular José Luis Bringa | Montevideo @| "Increíblemente los temas y el tiempo para nuestro país no pasan. Todo parece moverse en tiempos pretéritos. Una vez más se intenta por el Frente Amplio modificar una ley (la de Caducidad) que ha tenido por dos veces el respaldo de la gente. Esta vez, según el senador Agazzi, el argumento es que la ciudadanía no estaba lo `suficientemente informada`, cuando en octubre de 2009 el 53% de los votantes no votó la cláusula por la cual se anulaba dicha ley. O según el vicecanciller de la República, Roberto Conde, `si la gente se hubiese ilustrado más, quizá su voto hubiera sido diferente`. Anteriormente, en abril de 1989 la ley de Caducidad fue sometida a referéndum obteniendo el apoyo del 57% de los votantes. En aquel momento se hablaba de temor y de miedo. No debe existir en la historia del país ley con mayor respaldo popular que la ley de Caducidad. El pueblo, el cuerpo electoral haciendo uso de su soberanía en 

Trampear la voluntad popular José Luis Bringa | `Montevideo @`| "Increíblemente los temas y el tiempo para nuestro país no pasan. Todo parece moverse en tiempos pretéritos. Una vez más se intenta por el Frente Amplio modificar una ley (la de Caducidad) que ha tenido por dos veces el respaldo de la gente. Esta vez, según el senador Agazzi, el argumento es que la ciudadanía no estaba lo "suficientemente informada", cuando en octubre de 2009 el 53% de los votantes no votó la cláusula por la cual se anulaba dicha ley. O según el vicecanciller de la República, Roberto Conde, "si la gente se hubiese ilustrado más, quizá su voto hubiera sido diferente". Anteriormente, en abril de 1989 la ley de Caducidad fue sometida a referéndum obteniendo el apoyo del 57% de los votantes. En aquel momento se hablaba de temor y de miedo. No debe existir en la historia del país ley con mayor respaldo popular que la ley de Caducidad. El pueblo, el cuerpo electoral haciendo uso de su soberanía en forma libre y directa, se expresó rotunda y elocuentemente. No son demócratas los que no acatan las decisiones del pueblo. Ni la propia dictadura en 1980 desconoció un plebiscito adverso. Por otro lado, la ley de Caducidad hay que entenderla en el marco de lo que fue el Pacto del Club Naval y de una serie de leyes que se votaron para salir de la dictadura e ingresar a la democracia con el menor trauma posible. La ley de restitución de los funcionarios públicos, la ley de amnistía, por la cual se liberaron todos los presos políticos, computando tres días por cada día de prisión, y la ley de amnistía para los presos comunes. Razonando por el absurdo y siguiendo los planteamientos de Agazzi y Conde, podríamos sostener que el pueblo no estaba lo suficientemente "informado e ilustrado" cuando los votó a ellos para gobernar. Pero somos demócratas y acatamos lo que vota la gente. No quieran ustedes interpretar a la gente. Si hubo plebiscitos y referendos donde la gente sabía qué votaba, fueron precisamente éstos, donde lo que estaba en juego no era la caducidad de la pretensión punitiva del Estado, sino la paz del país. Doña María y Don José sabían perfectamente qué se estaba votando. El veredicto popular es sagrado. No nos hagan pasar la vergüenza de vivir en un país donde no se respeta lo que vota la gente". Un juego peligroso Alejandro Ciasullo `| Montevideo @|` "Cada vez que Rafael Michelini abre la boca me asombra. Ahora invita a votar el proyecto de ley interpretativo de la ley de Caducidad a los únicos demócratas del FA, Saravia y Nin Novoa, y que luego se plebiscite. Esto es como hacer trampa al solitario, o este senador cree que la ciudadanía es tonta. ¿Qué pasa si el plebiscito rechaza por tercera vez la ley? ¿Se vuelve todo para atrás? Y si se aprueba, ¿la minoría que pierda puede proponer más plebiscitos y que gane el mejor de tres? Seguir plebiscitando una propuesta ya votada y rechazada, incluso bajo gobierno del FA, me parece una actitud peligrosa. Sepa el ciudadano que los golpes de Estado pueden darse de facto esgrimiendo armas, pero también en forma técnica, atropellando con formalidades y jurisprudencia. Este es el caso, pues obviamente las palabras plebiscito, mayoría y democracia, no figuran en el manual de estadista del FA." La muerte del Sr. Kirchner Ricardo González F. `| Montevideo @|` "Felicito al Sr. Senador Alfredo Solari por su actitud en el Senado de la República al homenajearse al ex presidente argentino. Ante la muerte de un ser humano, respeto, pero no la inconsecuencia de llegar al homenaje de alguien que en vida, como presidente y como copartícipe del poder posteriormente, procuró llevar por delante a dos presidentes uruguayos de absoluto diferente pensamiento político entre sí. Intentó "patotear" a todos los orientales con sucesivas "bravatas" en todos los foros de su país e internacionales. Promovió a Uruguay un juicio en un tribunal internacional, a sabiendas de la falsedad de sus razones, pero contando que ello era parte del armamento con que avasalló a varios (sobre todo a compatriotas suyos): la prepotencia. Esta aventura kirchnerista en La Haya buen dinero nos costó a todos los uruguayos. Recordemos que también estuvo indudablemente detrás del destrato al presidente de todos los uruguayos a que lo sometió su esposa-sucesora cuando asumió el cargo, destratándonos en consecuencia a todos los uruguayos, hubiéramos votado o no al Dr. Vázquez. Y recordemos aún que incluso hace pocos días, desde Gualeguaychú, continuó con sus diatribas contra nuestra nación. Me pareció correctísimo lo actuado y aplaudo al señor senador Solari. Respeto ante la muerte de un ser humano. Ni nos alegra ni entristece. Pero por más poco diplomático que quede y por mejor y "necesario" que sea llevarse bien con el gobierno argentino, no es con obsecuencias que lograremos los mejores resultados a nuestros intereses. Y si no se concuerda con esa posición, recúrrase a la opinión de quienes deben negociar cualquier cosa con esta Argentina gobernada (ahora, se supone a plenitud) por Cristina F. de K.". Paros y COFE Vecina indignada `| Montevideo @|` "¡Realmente es indignante lo de COFE. ¿Peleando por el mínimo de 6 horas de trabajo? ¡Es de no creer! No necesitan más nada que decir. Claramente se ve que son todos unos vagos, que no quieren trabajar. Que los echen a todos y tomen gente que realmente quiera y necesite trabajar. Están todos muy cómodos. O que los pasen a todos al sector privado, para que sepan lo que es bueno". OSE y la Ursea Andrés Freire `| Canelones @|` "Soy el titular del expediente 296/2009 presentado ante la Ursea en mayo de ese año, luego de gestiones infructuosas ante OSE donde literalmente me tomaron el pelo, ya que vivo en una zona de la ciudad de Progreso donde habitualmente hay baja presión de octubre hasta julio. Esta situación me afecta gravemente porque tengo el baño en la planta alta de mi casa. De la lectura del expediente se desprende que la única responsable es OSE, que desde 1992 no ha realizado las obras requeridas en la zona. Solicité que OSE arregle el problema y mientras tanto me exonere de parte de la tarifa, debido a que se me cobra como si yo tuviera el servicio en forma permanente como cualquier usuario, cosa que no es así. Si mañana yo dejara de pagar, OSE me cortaría el servicio, mientras que ellos escudándose en su propia ineficiencia se arrogan la potestad de cortarme el servicio o dármelo en forma deficitaria cuando se les antoja. Después de más de un año, la Ursea no ha podido obligar a OSE a hacer lo que tiene que hacer. Me han atendido muy amablemente y el expediente ha recorrido todos los pasos, pero se viene otro verano y las soluciones no aparecen. Estoy pues muy disconforme. No tendrían que haber cambiado el directorio de la Ursea; tendrían que haberla eliminado, porque de mi cartita de reclamo se generó un expediente de más de 100 hojas, pero las soluciones no aparecen". Leonel Viera y El Cilindro Arq. Roberto Falco *`| Montevideo @|`* "Un ícono de la ingeniería nacional y mundial. La idea más brillante que se aportó al hormigón armado en los primeros 50 años del S. XX. No lo digo yo. Lo dijo el Ing. Mario G. Salvadori, Decano de la Columbia University in the City of New York, en un viaje a los Estados Unidos que tuve el privilegio de ir con Leonel Viera en el año 1960. No es el único aporte que realizó Leonel Viera para concretar avances de la ingeniería, pero quedémonos con éste. El proyecto fue motivo de inspiración para la construcción del Madison Square Garden de Nueva York, que se realizó con el mismo procedimiento; el Aeropuerto Dulles en Washington, que no es circular pero tiene un techo colgante en catenaria y otras obras más de envergadura. No conozco las razones por las que colapsó el Cilindro, pero, si para evitar que las goteras afectaran a los espectadores se le colocaban telas colgadas del techo, éstas habrían servido de mortaja para los que, la noche anterior al colapso, asistían a un espectáculo en ese lugar. Para realizar el mantenimiento de algo hay que conocer las causas que puedan afectarlo. Es como si un médico tratara a un paciente de algo que no sabe, lo que le produce la patología, y le hace tratamientos que no inciden sobre la enfermedad. Primero hay que saber cuál es la causa y después actuar. Ya en el año 1958, Leonel Viera advirtió que el mantenimiento de la estructura no era la correcta porque el agua ya estaba corrosionando los hierros. Por lo que he leído en los medios de comunicación, a los técnicos que actuaron y actúan en la problemática, no les he oído advertir del efecto de la "Stress Corrotion", que como dije antes, ya lo había advertido Viera. ¿No será ésta la causa? ¿Por qué no indagar esta posible patología? Si esto fuera así, ha habido una omisión muy lamentable de quienes actuaron en el mantenimiento durante 54 años. Por suerte no hay que lamentar víctimas humanas, pero sí hay que lamentar el colapso de ese gigante aplaudido en el mundo entero por los técnicos más calificados. Mi homenaje al genio es éste: se produjo un hecho imperdonable, colapsó el Cilindro Municipal. Hay que recuperarlo". Reserva de pasajes P.G.O. `| Montevideo @|` "Desde hace dos años que viajo diariamente desde Maldonado hasta Montevideo utilizando los servicios de la compañía Copsa. Para poder contar con asiento, reservo el mismo vía web desde la página de dicha empresa de transporte. Pero desde hace más de dos semanas que el servicio de reservas no está disponible, no habiendo en la página principal ninguna referencia al problema. El personal de atención al público tampoco tiene noticias de lo que ocurre con dicho servicio, limitándose a responder: "me parece que hay analistas trabajando en el problema". Quisiera conocer de parte de las autoridades de la empresa una fecha probable de resolución del problema. Como dato anecdótico, recuerdo que luego del gran incendio en el Palacio de la Luz los sistemas informáticos estaban funcionando a los pocos días de ocurrido el tremendo siniestro". El País Digital No salgas a la calle sin saber de qué se habla...


In [87]:
print(lines[80883])

Trampear la voluntad popular José Luis Bringa | Montevideo @| "Increíblemente los temas y el tiempo para nuestro país no pasan. Todo parece moverse en tiempos pretéritos. Una vez más se intenta por el Frente Amplio modificar una ley (la de Caducidad) que ha tenido por dos veces el respaldo de la gente. Esta vez, según el senador Agazzi, el argumento es que la ciudadanía no estaba lo `suficientemente informada`, cuando en octubre de 2009 el 53% de los votantes no votó la cláusula por la cual se anulaba dicha ley. O según el vicecanciller de la República, Roberto Conde, `si la gente se hubiese ilustrado más, quizá su voto hubiera sido diferente`. Anteriormente, en abril de 1989 la ley de Caducidad fue sometida a referéndum obteniendo el apoyo del 57% de los votantes. En aquel momento se hablaba de temor y de miedo. No debe existir en la historia del país ley con mayor respaldo popular que la ley de Caducidad. El pueblo, el cuerpo electoral haciendo uso de su soberanía en 

##### Solucion

In [88]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto entre | | - (con cierto formato)
pattern = r"\| \w*? .\|"
results = re.findall(pattern, str_text)
print(len(results))
print(len(set(results)))
for example in set(results):
  print(example)


4592
49
| Tacuarembó @|
| Salto @|
| Maldonado (|
| Perú @|
| Florida @|
| Suiza @|
| Rocha *|
| Panamá @|
| Montevideo *|
| Argentina @|
| Antel @|
| Agentina @|
| México @|
| Colonia @|
| Francia @|
| Alemania @|
| Maldonado @|
| Soriano *|
| Brasil @|
| Australia @|
| Canadá @|
| España @|
| Colonia *|
| Venezuela @|
| LATU @|
| Rivera @|
| Ecqus @|
| Montevideo (|
| BPS @|
| Lavalleja @|
| Copsa @|
| Israel @|
| Diputado *|
| Artigas @|
| Flores @|
| Canelones *|
| Pocitos @|
| BID @|
| Durazno @|
| Chile @|
| Canelones @|
| Lavalleja *|
| Rocha @|
| Paysandú *|
| Montevideo @|
| Presidente @|
| Paysandú @|
| Soriano @|
| Maldonado *|


In [89]:
str_text = auxiliar_full_lines

pattern = r"\| \w*? .?\|"
results = re.findall(pattern, str_text)
print(len(results))
print(len(set(results)))
for example in set(results):
  print(example)


# CONCLUSION
# tengo que eliminar todo esto


5959
84
| Recomendado |
| Salto @|
| Suiza @|
| Rocha *|
| Argentina @|
| insertar |
| Alemania @|
| Soriano *|
| Gamexán |
| Australia @|
| Colonia |
| Corresponsal |
| Actor |
| Diputado *|
| Flores @|
| Canelones *|
| Videojuegos |
| Presidente @|
| Paysandú @|
| peñarol |
| ESTEIO |
| cancelar |
| cable |
| Agentina @|
| Francia @|
| cantando |
| Brasil @|
| Venezuela @|
| Canadá @|
| LATU @|
| Colonia *|
| gargano |
| ARTIGAS |
| Israel @|
| Pocitos @|
| Marte |
| Opinión |
| Televisión |
| aceptacion |
| Soriano @|
| Canelones |
| Tacuarembó @|
| Florida @|
| adaptaciones |
| todos |
| Antel @|
| México @|
| España @|
| Titán |
| Ecqus @|
| Lavalleja @|
| formulario |
| xvi |
| ingresar |
| BID @|
| AFP |
| Lavalleja *|
| Canelones @|
| Rocha @|
| Maldonado (|
| Perú @|
| Panamá @|
| Montevideo *|
| futuro |
| Colonia @|
| Maldonado @|
| Rivera @|
| Montevideo (|
| CORRESPONSAL |
| VJ |
| BPS @|
| Copsa @|
| Artigas @|
| estrategia |
| Montevideo |
| Durazno @|
| Chile @|
| ENVIA

In [90]:
print("ANTES:")
pattern = r"\| \w*? .?\|"
results = re.findall(pattern, str_text)
print(f'cantidad de ocurrencias: {len(results)}')

# analisis de recorrer todo el texto
replace_pattern = r"\| \w*? .?\|"
total_result = re.sub(replace_pattern, '', str_text)  

print("DESPUES:")
pattern = r"\| \w*? .?\|"
results = re.findall(pattern, total_result)
print(f'cantidad de ocurrencias: {len(results)}')


ANTES:
cantidad de ocurrencias: 5959
DESPUES:
cantidad de ocurrencias: 0


In [91]:

replace_pattern = r"\| \w*? .?\|"
total_result = re.sub(replace_pattern, '', lines[80883])  

print(total_result)

Trampear la voluntad popular José Luis Bringa  "Increíblemente los temas y el tiempo para nuestro país no pasan. Todo parece moverse en tiempos pretéritos. Una vez más se intenta por el Frente Amplio modificar una ley (la de Caducidad) que ha tenido por dos veces el respaldo de la gente. Esta vez, según el senador Agazzi, el argumento es que la ciudadanía no estaba lo `suficientemente informada`, cuando en octubre de 2009 el 53% de los votantes no votó la cláusula por la cual se anulaba dicha ley. O según el vicecanciller de la República, Roberto Conde, `si la gente se hubiese ilustrado más, quizá su voto hubiera sido diferente`. Anteriormente, en abril de 1989 la ley de Caducidad fue sometida a referéndum obteniendo el apoyo del 57% de los votantes. En aquel momento se hablaba de temor y de miedo. No debe existir en la historia del país ley con mayor respaldo popular que la ley de Caducidad. El pueblo, el cuerpo electoral haciendo uso de su soberanía en forma libre y d

#### UPDATE: Tengo que seguir revisando casos entre | pipes |

### String "El País Digital" al final


In [92]:
print(lines[20643])

Todos los murguistas del presidente ¿Te interesa esta noticia?   | Pablo Melgar Los sectores más enfrentados con el gobierno son los más castigados en el carnaval. Adeom, COFE, los anestesistas y la oposición, son el blanco predilecto para las críticas de las murgas más populares, que admiten sin ruborizarse que son oficialistas. El olfato de los letristas de las murgas indica que los conflictos sindicales y el Mundial de Fútbol fueron los temas centrales de 2010. Dentro de los gremios, Adeom se lleva todas las menciones, pero también hay espacio para COFE y AEBU. Tres sindicatos que se enfrentaron con el gobierno. Sin embargo, los partidos de oposición y el reclamo de la anulación de la ley de Caducidad son un refugio ineludible para la mayoría de los conjuntos. Otro tema al que todas las murgas le dedican buena parte del espectáculo son los casos de corrupción en la Armada. Anestesistas y escribanos y sus respectivos conflictos con el gobierno también son tema para las m

Todos los murguistas del presidente ¿Te interesa esta noticia?   | Pablo Melgar Los sectores más enfrentados con el gobierno son los más castigados en el carnaval. Adeom, COFE, los anestesistas y la oposición, son el blanco predilecto para las críticas de las murgas más populares, que admiten sin ruborizarse que son oficialistas. El olfato de los letristas de las murgas indica que los conflictos sindicales y el Mundial de Fútbol fueron los temas centrales de 2010. Dentro de los gremios, Adeom se lleva todas las menciones, pero también hay espacio para COFE y AEBU. Tres sindicatos que se enfrentaron con el gobierno. Sin embargo, los partidos de oposición y el reclamo de la anulación de la ley de Caducidad son un refugio ineludible para la mayoría de los conjuntos. Otro tema al que todas las murgas le dedican buena parte del espectáculo son los casos de corrupción en la Armada. Anestesistas y escribanos y sus respectivos conflictos con el gobierno también son tema para las murgas que le dedican mucho espacio y críticas. La batalla interna en el Frente Amplio y el Pit-Cnt es tocada por varios conjuntos, que en todos los casos les aconsejan "defender la unidad" para que "no los coman los de afuera". El abogado Gonzalo Fernández, ex secretario de Presidencia y ex ministro del gobierno de Tabaré Vázquez, también es fustigado por el caso que dejó sin antecedentes penales a los hermanos Peirano Basso. Abandono. Agarrate Catalina, la murga que realizó el jingle de la campaña del presidente José Mujica, comienza su espectáculo ironizando sobre su abandono al primer mandatario. Sin profundizar demasiado, en la primera parte del espec-táculo hacen una rápida mirada por los personajes del mundo sindical. Hay referencias a Juan Castillo, Pablo Cabrera, José Lorenzo López y los dirigentes de Adeom y AEBU. La Catalina, varias veces ganadora del certamen, provocó polémica este año por un cuplé dedicado a la violencia. "Yo soy el terror de la sociedad / el plan perfecto que ha salido mal / vengo del basurero que el sistema dejó al costado / las leyes del mercado me convirtieron en funcional / soy un montón de mierda brotando de las alcantarillas / soy una pesadilla de la que no vas a despertar", dice la letra, una de las más aplaudidas en el Teatro de Verano. Danilo. La murga Falta y Resto, una de las más populares del carnaval, apostaba fuerte a su cuplé "Juancito atrás del mostrador", una crítica a quienes llegan a un sitio de privilegio y se olvidan de sus amigos. Para quienes lo vieron se trata de una feroz crítica al gobierno. Sin embargo, el 1° de febrero, día de la presentación frente al jurado en el Teatro de Verano, la pieza no apareció en el espectáculo. Los comentarios de la hinchada no se hicieron esperar. Muchos de los seguidores de la murga especularon con que la posible presencia en las gradas del vicepresidente Danilo Astori, un hincha histórico de La Falta, inhibió a los componentes del conjunto que finalmente resolvieron no presentar el cuplé. Ese día también resolvieron excluir el cuplé llamado "Bruno Díaz", que habían presentado en la prueba de admisión, lo que les costó una sanción. Quienes vieron la presentación completa del espectáculo en otros tablados, narraron a El País que "Juancito atrás del mostrador" narra la historia de un grupo de amigos que se reunían habitualmente en un bar hasta que uno de ellos, Juan, tiene la posibilidad de comprar el comercio. Cuando Juan pasa al otro lado del mostrador ve la realidad de otra forma y comienza a actuar diferente frente a sus amigos. La anécdota es utilizada por la murga para criticar, sin nombrarlos, a los distintos actores de gobierno que hasta no hace mucho eran simples dirigentes políticos. Para Hugo Brocos, letrista y fundador junto a Raúl Castro de Falta y Resto, el cuplé de Juancito se retiró por razones de tiempo. "No lo hicimos porque nos pasábamos de tiempo", aclaró el murguista, quien no ocultó la cercanía de Astori con el grupo. "Danilo es un hincha más que en este momento es vicepresidente. Él se sube a la bañadera cuando quiere, a veces viene a los ensayos y se toma un whisky con nosotros. Dice eso me gusta, eso no me gusta, lo escuchamos, pero al final decidimos nosotros", dijo Brocos. El viernes por la tarde el director de la Falta, Raúl Castro, viajó a Gualeguaychú donde la municipalidad le otorgó un reconocimiento. La murga fue la última en tocar antes del cierre del puente General San Martín y la primera en cruzarlo tras su apertura. Falta y Resto es de las murgas que tiene público propio en el exterior. `El País Digital`


In [93]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto -El País Digital-
pattern = r"El País Digital"
results = re.findall(pattern, str_text, re.IGNORECASE)
print(len(results))

# cantidad de ocurrencias con texto -El País Digital- al final
pattern_1 = r"(AFP)? El País Digital\n"
results_1 = re.findall(pattern_1, str_text, re.IGNORECASE)
print(f'Con texto "El País Digital" al final de la linea" - {len(results_1)}')


# analizo la diferencia
pattern_diff = r"....... El País Digital...."
results_diff = re.findall(pattern_diff, str_text, re.IGNORECASE)
print(results_diff[:50])

pattern_diff = r"......meses. El País Digital.........."
results_diff = re.findall(pattern_diff, str_text, re.IGNORECASE)
print(f"Texto con formato 'seis meses. El País Digital se reserva ...' - {len(results_diff)}")
print(results_diff[:50])

pattern_diff = r"......[^meses.] El País Digital...."
results_diff = re.findall(pattern_diff, str_text, re.IGNORECASE)
print(results_diff[:50])

pattern_diff = r"........ a El País Digital...."
results_diff = re.findall(pattern_diff, str_text, re.IGNORECASE)
print(f"Textos con el estilo 'dijo/dijeron/informo... a El País Digital' - {len(results_diff)}")


pattern_diff = r".......... de El País Digital...."
results_diff = re.findall(pattern_diff, str_text, re.IGNORECASE)
print(f"Textos con el estilo '.. de El País Digital' - {len(results_diff)}")
print(results_diff[:50])

pattern_diff = r"........ [^meses.][^a][^de] El País Digital...."
results_diff = re.findall(pattern_diff, str_text, re.IGNORECASE)
print(results_diff[:50])

pattern_diff = r"........ AFP El País Digital."
results_diff = re.findall(pattern_diff, str_text, re.IGNORECASE)
print(f"Textos con el estilo '.. AFP El País Digital' EL TEXTO NO ESTA AL FINAL DEL STRING - {len(results_diff)}")



# CONCLUSION:
# Hay casos que no se deben eliminar, pertenecen a la redaccion.
# El mismo string esta en mayusculas y minusculas
# Casos a borrar: 
#   - (AFP)? El País Digital\n  --> el texto esta al final, a veces puede estar acompaniado de AFP.
#   - AFP El País Digital.  --> el texto NO esta al final, ESTA acompaniado de AFP.

# Casos a mantener
#   - tiene algo de la forma 'seis meses. El País Digital se reserva ...'  -> esto lo analizo mas adelante
#   - referencia a alguien hablando "a El Pais Digital"
#   - estilo ".. de El País Digital"

0
Con texto "El País Digital" al final de la linea" - 0
[]
Texto con formato 'seis meses. El País Digital se reserva ...' - 0
[]
[]
Textos con el estilo 'dijo/dijeron/informo... a El País Digital' - 0
Textos con el estilo '.. de El País Digital' - 0
[]
[]
Textos con el estilo '.. AFP El País Digital' EL TEXTO NO ESTA AL FINAL DEL STRING - 0


In [94]:
# REEMPLAZO
testing_str = lines[20643]

replace_pattern = r"(AFP)? El País Digital\n"
result = re.sub(replace_pattern, '', testing_str, re.IGNORECASE)  

replace_pattern = r"AFP El País Digital."
result = re.sub(replace_pattern, '', result, re.IGNORECASE)  
print(result)


Todos los murguistas del presidente ¿Te interesa esta noticia?   | Pablo Melgar Los sectores más enfrentados con el gobierno son los más castigados en el carnaval. Adeom, COFE, los anestesistas y la oposición, son el blanco predilecto para las críticas de las murgas más populares, que admiten sin ruborizarse que son oficialistas. El olfato de los letristas de las murgas indica que los conflictos sindicales y el Mundial de Fútbol fueron los temas centrales de 2010. Dentro de los gremios, Adeom se lleva todas las menciones, pero también hay espacio para COFE y AEBU. Tres sindicatos que se enfrentaron con el gobierno. Sin embargo, los partidos de oposición y el reclamo de la anulación de la ley de Caducidad son un refugio ineludible para la mayoría de los conjuntos. Otro tema al que todas las murgas le dedican buena parte del espectáculo son los casos de corrupción en la Armada. Anestesistas y escribanos y sus respectivos conflictos con el gobierno también son tema para las m

In [95]:
#  HACER!

str_text = auxiliar_full_lines

print('ANTES:::')
pattern = r"El País Digital"
results = re.findall(pattern, str_text, re.IGNORECASE)
print(f"Ocurrencias -El País Digital- : {len(results)}")

pattern_1 = r"(AFP)? El País Digital\n"
results_1 = re.findall(pattern_1, str_text, re.IGNORECASE)
print(f'Ocurrencias "El País Digital" al final de la linea" : {len(results_1)}')

pattern_5 = r"AFP El País Digital."
results_5 = re.findall(pattern_5, str_text, re.IGNORECASE)
print(f"Ocurrencias '.. AFP El País Digital' EL TEXTO NO ESTA AL FINAL DEL STRING : {len(results_5)}")

pattern_2 = r"......meses. El País Digital.........."
results_2 = re.findall(pattern_2, str_text, re.IGNORECASE)
print(f"Ocurrencias 'seis meses. El País Digital se reserva ...' : {len(results_2)}")

pattern_3 = r"........ a El País Digital...."
results_3 = re.findall(pattern_3, str_text, re.IGNORECASE)
print(f"Ocurrencias 'dijo/dijeron/informo... a El País Digital' : {len(results_3)}")

pattern_4 = r".......... de El País Digital...."
results_4 = re.findall(pattern_4, str_text, re.IGNORECASE)
print(f"Ocurrencias '.. de El País Digital' : {len(results_4)}")

# REEMPLAZO!

replace_pattern = r"(AFP)? El País Digital\n"
result = re.sub(replace_pattern, '', str_text, re.IGNORECASE)  

replace_pattern = r"AFP El País Digital."
result = re.sub(replace_pattern, '', result, re.IGNORECASE)  

# FIN REEMPLAZO!

print('DESPUES:::')
pattern = r"El País Digital"
results = re.findall(pattern, result, re.IGNORECASE)
print(f"Ocurrencias -El País Digital- : {len(results)}")

pattern_1 = r"(AFP)? El País Digital\n"
results_1 = re.findall(pattern_1, result, re.IGNORECASE)
print(f'Ocurrencias "El País Digital" al final de la linea" : {len(results_1)}')

pattern_5 = r"AFP El País Digital."
results_5 = re.findall(pattern_5, result, re.IGNORECASE)
print(f"Ocurrencias '.. AFP El País Digital' EL TEXTO NO ESTA AL FINAL DEL STRING : {len(results_5)}")

pattern_2 = r"......meses. El País Digital.........."
results_2 = re.findall(pattern_2, result, re.IGNORECASE)
print(f"Ocurrencias 'seis meses. El País Digital se reserva ...' : {len(results_2)}")

pattern_3 = r"........ a El País Digital...."
results_3 = re.findall(pattern_3, result, re.IGNORECASE)
print(f"Ocurrencias 'dijo/dijeron/informo... a El País Digital' : {len(results_3)}")

pattern_4 = r".......... de El País Digital...."
results_4 = re.findall(pattern_4, result, re.IGNORECASE)
print(f"Ocurrencias '.. de El País Digital' : {len(results_4)}")


## REVISAR ##
# no se si esta funcionando

ANTES:::
Ocurrencias -El País Digital- : 0
Ocurrencias "El País Digital" al final de la linea" : 0
Ocurrencias '.. AFP El País Digital' EL TEXTO NO ESTA AL FINAL DEL STRING : 0
Ocurrencias 'seis meses. El País Digital se reserva ...' : 0
Ocurrencias 'dijo/dijeron/informo... a El País Digital' : 0
Ocurrencias '.. de El País Digital' : 0
DESPUES:::
Ocurrencias -El País Digital- : 0
Ocurrencias "El País Digital" al final de la linea" : 0
Ocurrencias '.. AFP El País Digital' EL TEXTO NO ESTA AL FINAL DEL STRING : 0
Ocurrencias 'seis meses. El País Digital se reserva ...' : 0
Ocurrencias 'dijo/dijeron/informo... a El País Digital' : 0
Ocurrencias '.. de El País Digital' : 0


### Texto "El País Digital se reserva el derecho de editar los mensajes que usted envíe a los efectos de su mejor comprensión por otros usuarios. Nuevo seudonimo"


In [96]:
print(lines[137])

Detenida se prendió fuego en seccional policial ¿Te interesa esta noticia?     Una mujer fue trasladada en estado delicado al Centro Nacional de Quemados (Cenaque), tras prenderse fuego en una Seccional 9o. La joven, de 26 años, había sido detenida en el marco de la investigación por el hurto de una moto que finalmente encontraron en su vivienda. Sufrió quemaduras de segundo y tercer grado en gran parte de su cuerpo y en vías respiratorias. Es ésta la segunda vez que un detenido prende fuego un colchón e intenta inmolarse. RIVERA - Freddy Fernández Carranza Ver Comentarios Filtrar por: Si desea comentar los contenidos de nuestras noticias, utilice el formulario y envíenos su comentario. REGLAS Y NORMAS Procesando.. Usuario: Solo usuarios registrados pueden comentar y/o denunciar. Mantenga y vigile el nivel de debate y recuerde que nuestras Normas de Participación implican obligaciones y responsabilidades. Contraseña: | cancelar | Si usted considera que se ha incurrido agrav

Detenida se prendió fuego en seccional policial ¿Te interesa esta noticia?     Una mujer fue trasladada en estado delicado al Centro Nacional de Quemados (Cenaque), tras prenderse fuego en una Seccional 9o. La joven, de 26 años, había sido detenida en el marco de la investigación por el hurto de una moto que finalmente encontraron en su vivienda. Sufrió quemaduras de segundo y tercer grado en gran parte de su cuerpo y en vías respiratorias. Es ésta la segunda vez que un detenido prende fuego un colchón e intenta inmolarse. RIVERA - Freddy Fernández Carranza Ver Comentarios Filtrar por: Si desea comentar los contenidos de nuestras noticias, utilice el formulario y envíenos su comentario. REGLAS Y NORMAS Procesando.. Usuario: Solo usuarios registrados pueden comentar y/o denunciar. Mantenga y vigile el nivel de debate y recuerde que nuestras Normas de Participación implican obligaciones y responsabilidades. Contraseña: | cancelar | Si usted considera que se ha incurrido agravios o no se respeta el reglamento de esta sección, puede DENUNCIAR al autor. En ese caso, automáticamente ese mensaje desaparece y es enviado al correo del Administrador de Foros/Comentarios. El Administrador puede avalar su decisión o discrepar con ella, en cuyo caso el mensaje es restituido. Se advierte que la reiteración de violaciones al reglamento, tanto como la reiteración de Denuncias injustificadas, pueden determinar que el usuario sea borrado del registro, perdiendo sus privilegios por seis meses. `El País Digital se reserva el derecho de editar los mensajes que usted envíe a los efectos de su mejor comprensión por otros usuarios. Nuevo seudonimo:`


#### Solucion

In [97]:
str_text = auxiliar_full_lines
# cantidad de ocurrencias con texto -El País Digital-
pattern = r"El Pais Digital se reserva el derecho de editar"
results = re.findall(pattern, str_text)
print(len(results))

# cantidad de ocurrencias con texto -El País Digital- al final
pattern = r"El Pais Digital se reserva el derecho de editar los mensajes que usted envie a los efectos de su mejor comprension por otros usuarios. (Nuevo seudonimo:)?"
results_1 = re.findall(pattern, str_text)
print(f'Con texto "El Pais Digital" al final de la linea" - {len(results_1)}')

0
Con texto "El Pais Digital" al final de la linea" - 0


### Texto ":: El Empresario ::" ya incluido en version de :: .* ::

In [100]:
print(lines[71850])

Absolut Vodka estrena diseño artesanal ¿Te interesa esta noticia?     Absolut Vodka, el vodka premium líder a nivel mundial, fue creado por Lars Olsson Smith y aún se produce bajo su método en la pequeña ciudad Ahüs en el sur de Suecia. En 1979 Absolut Vodka introdujo una botella de diseño pionero. Ahora Absolut Vodka presenta Absolut Vodka Crystal Botlle, diseñado como una verdadera pieza de arte, combinando en su botella los diseños de Skogsberg y Smart y el arte de Reijmyre, hecha a mano en su totalidad. Ver Comentarios Filtrar por: Si desea comentar los contenidos de nuestras noticias, utilice el formulario y envíenos su comentario. REGLAS Y NORMAS Procesando.. Usuario: Solo usuarios registrados pueden comentar y/o denunciar. Mantenga y vigile el nivel de debate y recuerde que nuestras Normas de Participación implican obligaciones y responsabilidades. Contraseña: | cancelar | Si usted considera que se ha incurrido agravios o no se respeta el reglamento de esta sección,

Absolut Vodka estrena diseño artesanal ¿Te interesa esta noticia?     Absolut Vodka, el vodka premium líder a nivel mundial, fue creado por Lars Olsson Smith y aún se produce bajo su método en la pequeña ciudad Ahüs en el sur de Suecia. En 1979 Absolut Vodka introdujo una botella de diseño pionero. Ahora Absolut Vodka presenta Absolut Vodka Crystal Botlle, diseñado como una verdadera pieza de arte, combinando en su botella los diseños de Skogsberg y Smart y el arte de Reijmyre, hecha a mano en su totalidad. Ver Comentarios Filtrar por: Si desea comentar los contenidos de nuestras noticias, utilice el formulario y envíenos su comentario. REGLAS Y NORMAS Procesando.. Usuario: Solo usuarios registrados pueden comentar y/o denunciar. Mantenga y vigile el nivel de debate y recuerde que nuestras Normas de Participación implican obligaciones y responsabilidades. Contraseña: | cancelar | Si usted considera que se ha incurrido agravios o no se respeta el reglamento de esta sección, puede DENUNCIAR al autor. En ese caso, automáticamente ese mensaje desaparece y es enviado al correo del Administrador de Foros/Comentarios. El Administrador puede avalar su decisión o discrepar con ella, en cuyo caso el mensaje es restituido. Se advierte que la reiteración de violaciones al reglamento, tanto como la reiteración de Denuncias injustificadas, pueden determinar que el usuario sea borrado del registro, perdiendo sus privilegios por seis meses. El País Digital se reserva el derecho de editar los mensajes que usted envíe a los efectos de su mejor comprensión por otros usuarios. Nuevo seudonimo: Con precios por las nubes las ventas de inmuebles siguen en alza y sólo 9% recurre al crédito. `:: El Empresario ::` Fuerte apuesta de AOC para ganar terreno en televisores Tras once años de presencia en Uruguay y líder en monitores (con 45% del mercado), la marca china AOC quiere fortalecer su posición también en televisores LCD y conquistar hasta un 15% de la torta de esos productos en el correr .. `:: El Empresario ::` En la opinión pública se habla de los malos funcionarios del Estado y lo que nunca se habla es de los muy buenos funcionarios que se desempeñan allí. Hay muchos con la camiseta bien puesta y mucho empuje. `:: El Empresario ::` Cuando el entonces Banco de Boston (hoy Itaú) lanzó los primeros beneficios asociados a la compra con tarjeta de crédito en Punta del Este, seguramente sus autoridades ni se imaginaron que una década después esos se .. `:: El Empresario ::` Con Facebook, Twitter y LinkedIn como líderes indiscutidos de la movida los uruguayos se sumaron en masa al uso de las redes sociales y, aunque las plataformas procuran distinguirse entre las de uso personal y profesional, los .. `:: El Empresario ::` Las empresas de Estados Unidos han saneado sus finanzas y ahora, con abundante dinero en los bolsillos, se disponen a gastar en fábricas, tiendas y personal. `:: El Empresario ::` Comenzaron trabajando en una tabla sobre dos caballetes, y hoy, casi un año más tarde, llevan realizadas unas 60 piezas publicitarias y ajustan detalles para presentar su nuevo programa televisivo de archivo "Sonríe (Te estamos ..


### BUSCAR CRUCIGRAMAS - algunos hechos por Leonardo Conde, palabra HORIZONTAL, tambien hay soluciones

In [101]:
str_text = auxiliar_full_lines

pattern = r"horizontales.*?\d\)"
results = re.findall(pattern, str_text, re.IGNORECASE)
print(len(results))

pattern = r"horizontales.*?\d\)............"
results = re.findall(pattern, str_text, re.IGNORECASE)
print(len(results))
for res in results[:50]:
  print(res)


# CONCLUSION: Elimino a todos los que cumplen esto


1133
1131
Horizontales. 1) Óxido de calcio. 
Horizontales 1) Criatura de pecho
HORIZONTALES 1) Cruel, refinada y
Horizontales 1) Sitio donde se pi
HORIZONTALES 1) Cálculo superstic
HORIZONTALES 1) Lecho nupcial. 6)
Horizontales 1) Juego de pelota e
Horizontales 2) Enredadera silves
Horizontales 1) Veneno. 7) Soldad
Horizontales 1) Pajarito conirros
HORIZONTALES 1) Perteneciente o r
HORIZONTALES 1) Región antigua de
Horizontales 1) Hombre tonto, o r
Horizontales 1) Castor, roedor fl
Horizontales 1) Utensilio de cost
Horizontales. 1) Palo en forma de 
Horizontales. 2) Sombrero de copa 
Horizontales 1) Exclamación tauri
Horizontales.    1) Superficie. 5) Bo
Horizontales 1) Vid levantada art
Horizontales 1) Plaza de las ciud
Horizontales 1) Demostración exce
Horizontales.   1) Valor o importanc
Horizontales 1) Califa de la dina
Horizontales 1) Hogar. 4) Instrum
Horizontales 1) Calisto, constela
Horizontales 1) El Hijo de Dios, 
Horizontales 1) Amapola. 6) Llega
Horizontales 2) Mazo pequeño

In [102]:
print('ANTES::')
print(f'Total de articulos: {len(lines)}')

regex =  r"horizontales.*?\d\)"
resulting_lines = list(filter(lambda line: not(re.search(regex, line, re.IGNORECASE)), lines))

print('DESPUES::')
print(f'Total de articulos: {len(resulting_lines)}')

ANTES::
Total de articulos: 120692
DESPUES::
Total de articulos: 119570


In [103]:
total_result = ''.join(resulting_lines)
pattern = r"horizontales.*?\d\)"
results = re.findall(pattern, total_result, re.IGNORECASE)
print(len(results))


0


#### CONTINUAR ANALIZANDO CASOS CON "Leonardo Conde"

index - 117992
'octubre 27 . A) Ducha, experimentada. B) Gusano de tierra. C) Celebracion, fiesta. D) Someter, tiranizar. E) Obstinacion ignorante. F) Elemental. G) Dieta, conjunto de sustancias que se ingieren. H) Pablo ..., nom-de-plume del poeta Neftali Reyes. I) Andre Marie ..., celebre matematico y fisico frances, padre del electromagnetismo. J) Primitivo, sin civilizacion avanzada. K) Molde empleado en la acunacion de monedas y medallas. L) Pastor. M) Fenomeno inmunologico por el que un organismo reconoce como extrano a un organo o tejido procedente de otro individuo. N) Moneda, pieza de metal. O) Participio irregular de "imprimir". P) Premio o galardon que se da por el trabajo. Q) Transparencia de los vinos dorados. R) Letrero que rodea la figura en las monedas o medallas. S) Pieles rojas, como Carlitos Tevez. T) Palmitato de sodio, explosivo usado en bombas incendiarias. U) Mamifero marino pisciforme, como la ballena, el delfin, etc. V) Alberto ..., celebrado actor comico argentino, desaparecido tragicamente. W) Planta cannabacea usada para elaborar la cerveza. X) Excelente, perfecto en su linea. Y) Personaje de la Comedia dell\'Arte, ataviado con mascara y traje a losanges de variados colores. SOLUCION 817: A) consul B) atolon C) Sanson D) ofender E) nomade F) adjunto G) lenoso H) acumen I) bloque J) asiduo K) Romeo L) Cronos M) aftosa N) salon O) insumo P) naipes Q) Punjab R) Esdras S) sismos T) cesped U) adios V) duques W) ociosos X) reyuno. Especial para El Pais. No 818. Por Leonardo Conde \n'


In [104]:
total_result = ''.join(resulting_lines)
pattern = r"Leonardo Conde"
results = re.findall(pattern, total_result, re.IGNORECASE)
print(len(results))


242


In [105]:
regex = r"Leonardo Conde"
resulting_lines = list(filter(lambda line: not(re.search(regex, line, re.IGNORECASE)), lines))

print(len(resulting_lines))

119463


### Texto EFE

In [120]:
# print('cantidad de ocurrencias EFE')

# replace_pattern = r" EFE "
# total_result = re.findall(replace_pattern, total_result)  
# print(len(total_result))

# replace_pattern = r"\(EFE\)"
# total_result = re.sub(replace_pattern, total_result)  
# print(len(total_result))


# results = re.findall(pattern, str_text, re.IGNORECASE)

cantidad de ocurrencias EFE
0


TypeError: sub() missing 1 required positional argument: 'string'

## elpais20140924173922Noticias.txt

In [108]:
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1SL4yUr2xgS2bX1_pzFWEOXXbrxNoSf0y' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1SL4yUr2xgS2bX1_pzFWEOXXbrxNoSf0y" -O elpais20140924173922Noticias.txt && rm -rf /tmp/cookies.txt
reader_3922 = open("elpais20140924173922Noticias.txt", "r+")
lines_3922 = reader_3922.readlines()
print(len(lines_3922))

--2022-10-24 20:07:05--  https://docs.google.com/uc?export=download&confirm=t&id=1SL4yUr2xgS2bX1_pzFWEOXXbrxNoSf0y
Resolving docs.google.com (docs.google.com)... 2800:3f0:4002:800::200e, 142.251.133.238
Connecting to docs.google.com (docs.google.com)|2800:3f0:4002:800::200e|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-00-1o-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/h1qs8rcfigdcsdrqd0u1b4ur6apvi5ls/1666652775000/05113844374629647830/*/1SL4yUr2xgS2bX1_pzFWEOXXbrxNoSf0y?e=download&uuid=203d76bd-e398-4577-b58c-7d77e6c3eb18 [following]
--2022-10-24 20:07:06--  https://doc-00-1o-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/h1qs8rcfigdcsdrqd0u1b4ur6apvi5ls/1666652775000/05113844374629647830/*/1SL4yUr2xgS2bX1_pzFWEOXXbrxNoSf0y?e=download&uuid=203d76bd-e398-4577-b58c-7d77e6c3eb18
Resolving doc-00-1o-docs.googleusercontent.com (doc-00-1o-docs.googleusercontent.com)... 2800:3f0:4002:80a:

In [109]:
len(lines_3922)

30534

In [110]:
!du -H elpais20140924173922Noticias.txt

123744	elpais20140924173922Noticias.txt


### String "Foto: -origen-"

In [111]:
print(lines_3922[11852])

TRÁNSITO CAPITALINO IMM aplicó 1.594 multas en feriado de Carnaval También derivó al depósito a 243 vehículos por considerar que representaban un peligro para el tránsito. Control de tránsito en Montevideo. FOTO: Archivo El País. Temas multas de tránsito jue mar 6 2014 13:21 La Intendencia de Montevideo aplicó 1.594 multas de tránsito en el fin de semana largo de Carnaval y trasladó al Depósito de Tránsito y Transporte a 243 vehículos por considerar que representaban un riesgo a los conductores tanto porque el chofer no tenía libreta o las condiciones del auto no eran buenas. Los operativos se realizaron desde el día viernes 28 de febrero hasta el martes 4 de marzo. En el operativo también se detuvieron a varias personas que participaron en picadas y fueron derivadas al Tribunal de Faltas, informó la comuna. Los inspectores aplicaron 357 multas por faltas de conducir, 189 por exceso de velocidad, 149 por condiciones antirreglamentarias, 144 por no uso de cinturón, 

TRÁNSITO CAPITALINO IMM aplicó 1.594 multas en feriado de Carnaval También derivó al depósito a 243 vehículos por considerar que representaban un peligro para el tránsito. Control de tránsito en Montevideo. `FOTO: Archivo El País`. Temas multas de tránsito jue mar 6 2014 13:21 La Intendencia de Montevideo aplicó 1.594 multas de tránsito en el fin de semana largo de Carnaval y trasladó al Depósito de Tránsito y Transporte a 243 vehículos por considerar que representaban un riesgo a los conductores tanto porque el chofer no tenía libreta o las condiciones del auto no eran buenas. Los operativos se realizaron desde el día viernes 28 de febrero hasta el martes 4 de marzo. En el operativo también se detuvieron a varias personas que participaron en picadas y fueron derivadas al Tribunal de Faltas, informó la comuna. Los inspectores aplicaron 357 multas por faltas de conducir, 189 por exceso de velocidad, 149 por condiciones antirreglamentarias, 144 por no uso de cinturón, 116 por no uso del casco, 89 por falta de documentación del vehículo, 51 por alcoholemia positiva, 45 por cruzar con roja, 35 por tener caño de escape libre, 22 por manejo imprudente, 22 por estacionamiento inadecuado y 375 de otras causas.  Vota por esta noticia:


In [112]:
print(lines_3922[17138])

accidente aéreo Sacarán el avión con helicópteros de la Fuerza Aérea argentina Esta tarde extraerán la aeronave del Río de la Plata. El Ministerio de Defensa realizó al mediodía una reunión para definir cómo sacarán el avión accidentado. Esta madrugada trasladaron el cuerpo del piloto a Argentina. El accidente ocurrió el martes pasado a 10 kilómetros de Carmelo. Foto: P. Clavijo Temas Iniciarían hoy la extracción del avión vie may 30 2014 12:55 Esta tarde será extraído el avión accidentado el martes pasado en el Río de la Plata, a 10 kilómetros de la ciudad de Carmelo, Colonia. Colaborarán uno o dos helicópteros de la Fuerza Aérea argentina, a pedido del Ministerio de Defensa, informó a El País Jorge Menéndez, subsecretario de esa cartera de Estado.   Aún no está definida exactamente la forma de extracción, que se establecerá en las próximas horas y en ella influirá también el estado del tiempo. Al mediodía se realizó "la reunión de preparación e

accidente aéreo Sacarán el avión con helicópteros de la Fuerza Aérea argentina Esta tarde extraerán la aeronave del Río de la Plata. El Ministerio de Defensa realizó al mediodía una reunión para definir cómo sacarán el avión accidentado. Esta madrugada trasladaron el cuerpo del piloto a Argentina. El accidente ocurrió el martes pasado a 10 kilómetros de Carmelo. `Foto: P. Clavijo` Temas Iniciarían hoy la extracción del avión vie may 30 2014 12:55 Esta tarde será extraído el avión accidentado el martes pasado en el Río de la Plata, a 10 kilómetros de la ciudad de Carmelo, Colonia. Colaborarán uno o dos helicópteros de la Fuerza Aérea argentina, a pedido del Ministerio de Defensa, informó a El País Jorge Menéndez, subsecretario de esa cartera de Estado.   Aún no está definida exactamente la forma de extracción, que se establecerá en las próximas horas y en ella influirá también el estado del tiempo. Al mediodía se realizó "la reunión de preparación entre los actores para determinar la forma y el momento, pero va a ser en el correr de la tarde. En principio se va a hacer con fuerzas del Ministerio de Defensa, la Prefectura, del Ejército y desde el Ministerio de Defensa pedimos, en base a un ofrecimiento que tuvimos, la colaboración de la Fuerza Aérea argentina con helicópteros apropiados para levantar este tipo de pesos que en Uruguay no existen", afirmó Menéndez. El avión será trasladado a Montevideo para que la Comisión Investigadora de Accidentes e Incidentes de Aviación (Ciaia) comience a investigar las causas del accidente aéreo.  Piloto. Esta madrugada trasladaron los restos de Leandro Larriera, piloto del avión accidentado el martes pasado en el Río de la Plata, a Buenos Aires. Tras las pericias forenses realizadas en segunda instancia en Colonia, la empresa Cordoez Aguirre reacondicionó el cuerpo y a las 4:30 trasladó el féretro desde el puerto de Colonia. Una segunda pericia forense solicitada por la justicia uruguaya motivó un insólito trasiego del féretro del piloto y retrasó el traslado de sus restos a Buenos Aires.  Aunque existía una autorización para el traslado del ataúd, cuando el vehículo de la empresa fúnebre Cordobez Aguirre arribó al puerto de Colonia, a las 16:20 horas, llegó una orden de la jueza Alexandra Facal, de no embarcarlo, debido a la necesidad de llevar a cabo una nueva pericia forense. Los propios familiares de la víctima ya habían retornado a Argentina, y esperaban el cuerpo de Larriera a las 17:30 en Buenos Aires. Tras las actuaciones correspondientes, de las que participó el cónsul César Mata y otros funcionarios, se resolvió trasladar el cuerpo a la morgue judicial, ubicada en el Cementerio de Colonia. Vota por esta noticia:


### Practicamente todo el siguiente texto

In [113]:
print(lines_3922[19825])

Limpieza del hogar con nueva línea de Lysoform ¿Te interesa esta noticia?   La compañía SC Johnson & Son presentó el nuevo Lysoform Aerosol en versión pocket de 55 cm3. La marca Lysoform en versión pocket elimina en un 99.9% virus y bacterias. Además, posee una presentación pequeña y compacta, que facilita su traslado del producto para hacer más fácil la vida cotidiana. Baños, vestuarios, transportes, oficinas, teléfonos, cambiadores de bebé, ascensores y picaportes integran una larga lista de aplicaciones de la marca de desinfección del hogar. Ver Comentarios Filtrar por: Si desea comentar los contenidos de nuestras noticias, utilice el formulario y envíenos su comentario. REGLAS Y NORMAS Procesando.. Usuario: Solo usuarios registrados pueden comentar y/o denunciar. Mantenga y vigile el nivel de debate y recuerde que nuestras Normas de Participación implican obligaciones y responsabilidades. Contraseña: | cancelar | Si usted considera que se ha incurrido agravios o n

Limpieza del hogar con nueva línea de Lysoform ¿Te interesa esta noticia?   La compañía SC Johnson & Son presentó el nuevo Lysoform Aerosol en versión pocket de 55 cm3. La marca Lysoform en versión pocket elimina en un 99.9% virus y bacterias. Además, posee una presentación pequeña y compacta, que facilita su traslado del producto para hacer más fácil la vida cotidiana. Baños, vestuarios, transportes, oficinas, teléfonos, cambiadores de bebé, ascensores y picaportes integran una larga lista de aplicaciones de la marca de desinfección del hogar. Ver Comentarios Filtrar por: Si desea comentar los contenidos de nuestras noticias, utilice el formulario y envíenos su comentario. REGLAS Y NORMAS Procesando.. Usuario: Solo usuarios registrados pueden comentar y/o denunciar. Mantenga y vigile el nivel de debate y recuerde que nuestras Normas de Participación implican obligaciones y responsabilidades. Contraseña: | cancelar | Si usted considera que se ha incurrido agravios o no se respeta el reglamento de esta sección, puede DENUNCIAR al autor. En ese caso, automáticamente ese mensaje desaparece y es enviado al correo del Administrador de Foros/Comentarios. El Administrador puede avalar su decisión o discrepar con ella, en cuyo caso el mensaje es restituido. Se advierte que la reiteración de violaciones al reglamento, tanto como la reiteración de Denuncias injustificadas, pueden determinar que el usuario sea borrado del registro, perdiendo sus privilegios por seis meses. El País Digital se reserva el derecho de editar los mensajes que usted envíe a los efectos de su mejor comprensión por otros usuarios. Nuevo seudonimo: Maximo caractéres: 600 ( restan: 600 Cuando ellos se convierten en papás primerizos mejora su imagen en el mundo laboral, aunque las empresas uruguayas en general no tienen políticas que atiendan esta realidad. :: El Empresario :: En EE.UU. protegen al rodeo de los coyotes y en Uruguay su uso es incipiente. :: El Empresario :: Nació en Montevideo hace 50 años. Se recibió de ingeniero agrónomo pero se especializó en Marketing, desde los 24 años siendo parte de la empresa y, gracias a ella, haciendo pasantías en otras en el exterior. Hoy, junto a otros .. :: El Empresario :: La representación local del grupo noruego Ragasco negocia con las distribuidoras de supergás la incorporación de una nuevas garrafas que se utilizan en Europa, Estados Unidos y países latinoamericanos como Venezuela y Chile. :: El Empresario :: La cadena dará un giro a su comunicación en busca de jugar fuerte como supermercado. :: El Empresario :: Los programas combinan clases online con algunos cursos presenciales permitiendo a más aspirantes sumarse a la maestría. :: El Empresario :: China, India, Brasil y Rusia sustituyen a EE.UU. y Europa como los mayores compradores de empresas. :: El Empresario ::


### el siguiente parece ser fecha y hora de publicacion + titular

In [114]:
print(lines_3922[30278])

Patronal del taxi movilizará 100 unidades al día hacia Economía La Patronal del Taxi aprobó por unanimidad "descolgarse" de los convenios de salarios, continuará enviando al seguro de paro a los choferes, movilizará 100 unidades por día hacia el Ministerio de Economía, y se opone a la entrega de más chapas. 14 agosto 2014 | 04:00 La Intendencia de Montevideo aseguró ayer que "no quedan partidas" de dinero por rendir cuentas y acusó a El País de "atacar con intencionalidad política a la institución" y "arrojar sombras sobre el honor de las personas". 12 agosto 2014 | 12:27 Vecinos denunciaron ruidos molestos y picadas que motivaron un operativo en conjunto con la Policía y el INAU. 12 agosto 2014 | 04:00 La Intendencia de Montevideo realizó 353 investigaciones administrativas en un año y destituyó a seis personas; en tanto la Justicia procesó a cinco de sus funcionarios. La Jurídica de IMM incrementó el número de expedientes tratados en 2013. 12 agosto 2014 | 04:00

Patronal del taxi movilizará 100 unidades al día hacia Economía La Patronal del Taxi aprobó por unanimidad "descolgarse" de los convenios de salarios, continuará enviando al seguro de paro a los choferes, movilizará 100 unidades por día hacia el Ministerio de Economía, y se opone a la entrega de más chapas. 14 agosto 2014 | 04:00 La Intendencia de Montevideo aseguró ayer que "no quedan partidas" de dinero por rendir cuentas y acusó a El País de "atacar con intencionalidad política a la institución" y "arrojar sombras sobre el honor de las personas". 12 agosto 2014 | 12:27 Vecinos denunciaron ruidos molestos y picadas que motivaron un operativo en conjunto con la Policía y el INAU. 12 agosto 2014 | 04:00 La Intendencia de Montevideo realizó 353 investigaciones administrativas en un año y destituyó a seis personas; en tanto la Justicia procesó a cinco de sus funcionarios. La Jurídica de IMM incrementó el número de expedientes tratados en 2013. 12 agosto 2014 | 04:00 Tres de los nuevos contenedores de residuos ubicados en el centro de Montevideo fueron quemados durante la madrugada del domingo y uno de los responsables fue detenido por la Policía. 10 agosto 2014 | 04:00 ¿Y usted con qué sueña? Todos tenemos derecho a soñar; es más, yo diría que tenemos el deber de hacerlo. Qué infelices deben ser las personas que no tienen sueños. A través de la edición del viernes de El País me enteré que la Intendencia capitalina tiene una página web denominada Proyecto Montevideo 2030, en la que todos podemos proponer ideas y sueños. 09 agosto 2014 | 04:00 De cara al 2030 la Intendencia de Montevideo propuso un debate en torno a los espacios públicos y grafitis. La mayoría coincide en que el enchastre no aporta a la convivencia, y el grafiti o los murales son otra cosa. 07 agosto 2014 | 13:50 La Intendencia de Montevideo incautó miles de medicamentos en ferias de la ciudad, algunos tenían el sello de ASSE. 07 agosto 2014 | 04:00 Mientras en la familia del taxi prosigue el conflicto por el envío al seguro de paro de 25 radiotelefonistas, los trabajadores sindicalizados en el Suatt criticaron con dureza las nuevas medidas de la Patronal que afectarían a 1.500 choferes. 07 agosto 2014 | 04:00 El Servicio de Inspección General de la Intendencia de Montevideo realizó diversos operativos en periferias de toda la ciudad. 05 agosto 2014 | 09:12 La concesión estaba vencida desde 2007 y la comuna estaba recibiendo $ 30.000 de canon más ajustes mensuales por IPC, lo que fue cuestionado por la oposición. Ahora el canon mínimo anual que pide la comuna es de $ 658.000. 05 agosto 2014 | 04:24 Adeom presentó ante la Comisión de Derechos Humanos de la Junta Departamental unos 25 casos de "discriminación" a funcionarios discapacitados o con problemas de salud. Algunos de los trabajadores afectados dieron sus testimonios. 05 agosto 2014 | 04:00 La Intendencia de Montevideo lanzó una licitación para comercializar el inmueble ubicado en la manzana comprendida entre Arenal Grande, Democracia y Gutiérrez, (ex Escuela de Varones). 04 agosto 2014 | 15:32 Las denuncias ante la comuna capitalina se presenten a través de la aplicación "Por mi barrio". 04 agosto 2014 | 09:44 Cayó árbol y dejó un cráter en la vereda Un árbol se desplomó en la madrugada del domingo sobre una casa de Carrasco, ubicada en Avenida Bolivia y Beyrouth. El incidente no provocó personas fallecidas ni heridos, según comentó a El País una mujer que habita justo en la casa de enfrente. 03 agosto 2014 | 04:04 El edificio del excine Trocadero será subdividido para la creación de cinco locales comerciales, que se sumarán al inaugurado en su majestuoso hall. La intendencia de Montevideo quiso impedirlo, pero fracasó por falta de herramientas legales. 02 agosto 2014 | 04:23 Después de recientes cuestionadas y cuestionables demoliciones de fincas con valores estéticos o históricos, la Intendencia de Montevideo está puliendo un proyecto de decreto para crear nuevas figuras de protección patrimonial. 01 agosto 2014 | 04:00 La jueza penal Beatriz Larrieu desarchivó el expediente en donde el ex edil nacionalista Daniel Graffigna demandó a jerarcas de la IMM por omisión y negligencia, después de la caída del techo del Cilindro Municipal, ocurrida en 2010. 31 julio 2014 | 09:38 La Intendencia de Montevideo afirma que entre el sábado y el lunes pasado fueron quemados 11 contenedores en el Centro y Ciudad Vieja. 31 julio 2014 | 04:00


### Texto "Otras notas de Editorial"

In [115]:
lines_3922[26340]

'Los efectivos militares están siendo repatriados desde Haití a Uruguay para continuar la investigación. :: Último Momento :: Meteorología pronostica que las máximas serán de 16° y las mínimas de 11°. :: Ciudades :: La Policía prestará especial atención a la vigilancia en las zonas aledañas al Montevideo Shopping, donde el domingo falleció un adolescente de 16 años a manos de un joven de 19, tras una grave trifulca, y monitorea mensajes .. :: Internacional :: La Justicia argentina buscaba ayer a los culpables del homicidio de Candela Rodríguez, la niña de 11 años cuyo cuerpo apareció en una bolsa luego de permanecer nueve días secuestrada. :: Último Momento :: La trágica noticia la confirmó el ministro de Defensa chileno, Andrés Allamand. :: Fútbol Nacional :: Peñarol lidera y espera Peñarol le ganó a Defensor Sporting 1 a 0, con gol de Walter López y es líder provisorio del Torneo Apertura, con 10 puntos. Los aurinegros esperan un tropiezo de Danubio, con 

Los efectivos militares están siendo repatriados desde Haití a Uruguay para continuar la investigación. :: Último Momento :: Meteorología pronostica que las máximas serán de 16° y las mínimas de 11°. :: Ciudades :: La Policía prestará especial atención a la vigilancia en las zonas aledañas al Montevideo Shopping, donde el domingo falleció un adolescente de 16 años a manos de un joven de 19, tras una grave trifulca, y monitorea mensajes .. :: Internacional :: La Justicia argentina buscaba ayer a los culpables del homicidio de Candela Rodríguez, la niña de 11 años cuyo cuerpo apareció en una bolsa luego de permanecer nueve días secuestrada. :: Último Momento :: La trágica noticia la confirmó el ministro de Defensa chileno, Andrés Allamand. :: Fútbol Nacional :: Peñarol lidera y espera Peñarol le ganó a Defensor Sporting 1 a 0, con gol de Walter López y es líder provisorio del Torneo Apertura, con 10 puntos. Los aurinegros esperan un tropiezo de Danubio, con 9 puntos ganados en tres partidos, mañana ante Rampla .. :: Basketball :: La selección uruguaya de básquetbol le ganó a su similar de Paraguay por 79 a 66, en su último partido de la fase inicial del Preolímpico de Mar de Plata. :: Nacional :: Los abogados defensores de Arana, Muñoz y Rosselli criticaron la falta de garantías en el proceso judicial por el caso de los casinos municipales: aducen que los exjerarcas de la IMM declararon en el juzgado en calidad de .. :: Nacional :: El sector del presidente Mujica dice que se tiene que ir hacia la "revolución" y el "socialismo". Los liderados por Michelini sostienen que "no es legítimo imponer" esa lectura al FA. :: Futbol Internacional :: La UEFA anunció que Diego Forlán no podrá jugar por el Inter en la fase de grupos de la Liga de Campeones por haber jugado con el Atlético la Europa League. `Otras notas de Editorial`\n

### Texto "EL PAÍS digital" al final.

In [116]:
lines_3922[25704]

'Destacados policiales Accidente con saldo fatal en el Cordón Un violento choque entre un Peugeot 106 y un taxímetro en la esquina de Maldonado y Juan Manuel Blanes dejó el saldo de una persona muerta y otra con traumatismos leves, informó a EL PAÍS digital el jefe de prensa de Bomberos Carlos Nicola. Pablo Durán, de 25 años, que viajaba en el Peugeot perdió la vida a causa de la colisión, explicó Nicola. Un tercer ocupante de ese vehículo, de 26 años, resultó con traumatismos leves y fue atendido en el lugar por un móvil de emergencia médica. Tanto el conductor del auto como el cuarto pasajero resultaron ilesos del accidente. La misma fortuna tuvo el chofer del taxímetro que al momento del choque no llevaba pasaje. El conductor del auto expresó que circulaba por Blanes y al llegar a Maldonado cruzó el semáforo con luz roja, colisionando con el taxímetro. Un cuidacoches le parte la cabeza a otro con un bate de béisbol En horas de la tardecita de ayer, efectivos pol

Destacados policiales Accidente con saldo fatal en el Cordón Un violento choque entre un Peugeot 106 y un taxímetro en la esquina de Maldonado y Juan Manuel Blanes dejó el saldo de una persona muerta y otra con traumatismos leves, informó a EL PAÍS digital el jefe de prensa de Bomberos Carlos Nicola. Pablo Durán, de 25 años, que viajaba en el Peugeot perdió la vida a causa de la colisión, explicó Nicola. Un tercer ocupante de ese vehículo, de 26 años, resultó con traumatismos leves y fue atendido en el lugar por un móvil de emergencia médica. Tanto el conductor del auto como el cuarto pasajero resultaron ilesos del accidente. La misma fortuna tuvo el chofer del taxímetro que al momento del choque no llevaba pasaje. El conductor del auto expresó que circulaba por Blanes y al llegar a Maldonado cruzó el semáforo con luz roja, colisionando con el taxímetro. Un cuidacoches le parte la cabeza a otro con un bate de béisbol En horas de la tardecita de ayer, efectivos policiales concurrieron a la calle Enrique Legrand y Rivera, ya que una persona se encontraba caída en la vía pública. En el lugar se supo que un hombre de 42 años, cuidacoches del lugar, había mantenido una discusión con otro sujeto por el lugar. En determinado momento, este último sacó un bate de béisbol de su bolso y le pegó en la cabeza. Al tiempo que el herido caía al pavimento el agresor se dio rápidamente a la fuga. El hombre herido fue atendido por un móvil de emergencia donde se le diagnosticó "traumatismo encéfalo craneano frontotemporal izquierdo", siendo derivado al Hospital de Clínicas. Investiga lo ocurrido la seccional 11ra. Seis menores rapiñaron casa de venta de ropa deportiva Ocurrió ayer en la tienda ubicada en 21 de Setiembre y José Ellauri. La víctima, de 26 años, dijo a la Policía que cerca de las 18 horas ingresaron seis sujetos al local aparentemente menores de edad solicitando precios de varios artículos. Se retiraron pero regresaron poco tiempo después gritando y amenazando a la encargada del comercio. Robaron dinero y una gran cantidad de artículos deportivos. Los delincuentes se dieron posteriormente a la fuga en un taxímetro. Investiga personal de la seccional 10ma. El comercio posee seguro. Tres menores rapiñan ómnibus de Raincoop Efectivos de Radio Patrulla concurrieron ayer a Juan José de Amezaga y Democracia. En ese lugar el chofer y guarda del coche de la Línea 79, con destino Ciudadela, denunciaron que cerca de las 21.00 horas partieron de la Terminal de Villa Española, donde subieron tres desconocidos de entre 13 y 14 años. Momentos después fueron amenazados con un arma de fuego, robándoles dinero y objetos personales, para darse luego rápidamente a la fuga. Investiga el delito la Comisariía 4ta. Rapiña a ómnibus de la empresa Coetc A las 11.10 horas de hoy, el vehículo con destino Saint Bois llegó hasta ese lugar, cuando el conductor observa que quedaba un único pasajero en el fondo el cual se había quedado dormido. Cuando se dirige a despertarlo, el sujeto saca una cuchilla de sus ropas y se la pone en el cuello al trabajador del transporte. Luego de conseguir sustraer el dinero recaudado se da rápidamente a la fuga. Efectivos de la seccional 21a. recorrieron la zona sin lograr hasta el momento resultados positivos. `EL PAÍS digital`


### Texto con formato (creo que al inicio):  "Montevideo, Uruguay | 05:34   - aa aa |"

In [117]:
lines_3922[875]

'Montevideo, Uruguay | 05:34   - Economía Informe | Considera alentadora la performance de la construcción aunque la ve muy dependiente de las plantas de celulosa y de Punta del Este Para Cinve la importación de maquinaria está enlentecida La compra de bienes de capital podría ser un indicio inquietante sobre la evolución que tendrá la inversión El Centro de Investigaciones Económicas (Cinve) puso una "nota de alerta" sobre "el pobre" desempeño reciente de las importaciones de bienes de capital y el efecto de esto sobre el nivel de la inversión futura. En su reporte del viernes 28 sobre Actividad y Comercio se evaluó el comportamiento de varios indicadores que podrían adelantar la evolución del Producto Interno Bruto en los últimos meses del año. Luego de repasar los indicadores sobre industria, importaciones y recaudación el Cinve sostiene que si bien la economía "está desacelerándose -como era normal y esperado- no lo estaría haciendo a un ritmo mayor al previsto

`Montevideo, Uruguay | 05:34   - Economía Informe | `Considera alentadora la performance de la construcción aunque la ve muy dependiente de las plantas de celulosa y de Punta del Este Para Cinve la importación de maquinaria está enlentecida La compra de bienes de capital podría ser un indicio inquietante sobre la evolución que tendrá la inversión El Centro de Investigaciones Económicas (Cinve) puso una "nota de alerta" sobre "el pobre" desempeño reciente de las importaciones de bienes de capital y el efecto de esto sobre el nivel de la inversión futura. En su reporte del viernes 28 sobre Actividad y Comercio se evaluó el comportamiento de varios indicadores que podrían adelantar la evolución del Producto Interno Bruto en los últimos meses del año. Luego de repasar los indicadores sobre industria, importaciones y recaudación el Cinve sostiene que si bien la economía "está desacelerándose -como era normal y esperado- no lo estaría haciendo a un ritmo mayor al previsto". La evolución de la importación de bienes de capital es el único indicador que no está mostrando señales alentadoras. Según las estimaciones de Cinve en base a los datos del Banco Central del Uruguay, la tasa de crecimiento subyacente a junio de 2006 "es incluso levemente negativa" en 2,3%. Este indicador es el que brinda señales adelantadas de más largo plazo "dado que pauta la evolución de la inversión física de la economía, condición necesaria para sustentar el crecimiento de los próximos años". Para los técnicos del Cinve, "resulta pertinente continuar monitoreando de forma cercana y atenta estos indicadores en los próximos meses". En cambio, el informe destaca el crecimiento sostenido en la industria y en especial en las empresas manufactureras concentradas en la exportación. Además de las cifras oficiales, el Cinve también estudia la tendencia -excluyendo los comportamientos volátiles- de la industria. Según sus cálculos, la tendencia subyacente en ese sector sin la refinería se encuentra creciendo a un ritmo del orden de 10% anual a mayo de 2006. En el caso de las exportaciones la tendencia subyacente marca que las ventas se están incrementando a "tasas aún elevadas" superiores al 11%. La recaudación de impuestos por el consumo interno "sigue aumentando a buen ritmo". La suba subyacente de la recaudación de IVA interno era de 8,6% real a mayo de este año. Este indicador "revela que el mercado interno está mostrando muy buen dinamismo", destaca el informe. CONSTRUCCION. El reporte de Cinve corrigió al alza sus proyecciones de crecimiento de la construcción luego de los resultados del primer trimestre. Ahora estima que el sector crecerá 11% en el año y que en el primer semestre la suba será de 14,4% respecto a igual período de 2005. Según los técnicos de Cinve, en los primeros tres meses la construcción ingresó "en una fase expansiva" dado que crece por encima de su tendencia de largo plazo. Su comportamiento se explica por las plantas de celulosa y las obras en Punta del Este. Para Cinve el sector debe lograr un crecimiento no dependiente de esos factores coyunturales.  Utilidades
